<?php

use Illuminate\Database\Seeder;
use App\models\Municipios;

class MunicipiosTableSeeder extends Seeder
{

    /**
     * Lista de los municipios.
     */
    private $data= array(
        array('codigo_dane'=> '05001', 'nombre'=> 'MEDELLIN', 'departamento'=> '05'),
        array('codigo_dane'=> '05002', 'nombre'=> 'ABEJORRAL', 'departamento'=> '05'),
        array('codigo_dane'=> '05004', 'nombre'=> 'ABRIAQUI', 'departamento'=> '05'),
        array('codigo_dane'=> '05021', 'nombre'=> 'ALEJANDRIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05030', 'nombre'=> 'AMAGA', 'departamento'=> '05'),
        array('codigo_dane'=> '05031', 'nombre'=> 'AMALFI', 'departamento'=> '05'),
        array('codigo_dane'=> '05034', 'nombre'=> 'ANDES', 'departamento'=> '05'),
        array('codigo_dane'=> '05036', 'nombre'=> 'ANGELOPOLIS', 'departamento'=> '05'),
        array('codigo_dane'=> '05038', 'nombre'=> 'ANGOSTURA', 'departamento'=> '05'),
        array('codigo_dane'=> '05040', 'nombre'=> 'ANORI', 'departamento'=> '05'),
        array('codigo_dane'=> '05042', 'nombre'=> 'SANTAFE DE ANTIOQUIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05044', 'nombre'=> 'ANZA', 'departamento'=> '05'),
        array('codigo_dane'=> '05045', 'nombre'=> 'APARTADO', 'departamento'=> '05'),
        array('codigo_dane'=> '05051', 'nombre'=> 'ARBOLETES', 'departamento'=> '05'),
        array('codigo_dane'=> '05055', 'nombre'=> 'ARGELIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05059', 'nombre'=> 'ARMENIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05079', 'nombre'=> 'BARBOSA', 'departamento'=> '05'),
        array('codigo_dane'=> '05086', 'nombre'=> 'BELMIRA', 'departamento'=> '05'),
        array('codigo_dane'=> '05088', 'nombre'=> 'BELLO', 'departamento'=> '05'),
        array('codigo_dane'=> '05091', 'nombre'=> 'BETANIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05093', 'nombre'=> 'BETULIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05101', 'nombre'=> 'CIUDAD BOLIVAR', 'departamento'=> '05'),
        array('codigo_dane'=> '05107', 'nombre'=> 'BRICEÑO', 'departamento'=> '05'),
        array('codigo_dane'=> '05113', 'nombre'=> 'BURITICA', 'departamento'=> '05'),
        array('codigo_dane'=> '05120', 'nombre'=> 'CACERES', 'departamento'=> '05'),
        array('codigo_dane'=> '05125', 'nombre'=> 'CAICEDO', 'departamento'=> '05'),
        array('codigo_dane'=> '05129', 'nombre'=> 'CALDAS', 'departamento'=> '05'),
        array('codigo_dane'=> '05134', 'nombre'=> 'CAMPAMENTO', 'departamento'=> '05'),
        array('codigo_dane'=> '05138', 'nombre'=> 'CAÑASGORDAS', 'departamento'=> '05'),
        array('codigo_dane'=> '05142', 'nombre'=> 'CARACOLI', 'departamento'=> '05'),
        array('codigo_dane'=> '05145', 'nombre'=> 'CARAMANTA', 'departamento'=> '05'),
        array('codigo_dane'=> '05147', 'nombre'=> 'CAREPA', 'departamento'=> '05'),
        array('codigo_dane'=> '05148', 'nombre'=> 'EL CARMEN DE VIBORAL', 'departamento'=> '05'),
        array('codigo_dane'=> '05150', 'nombre'=> 'CAROLINA', 'departamento'=> '05'),
        array('codigo_dane'=> '05154', 'nombre'=> 'CAUCASIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05172', 'nombre'=> 'CHIGORODO', 'departamento'=> '05'),
        array('codigo_dane'=> '05190', 'nombre'=> 'CISNEROS', 'departamento'=> '05'),
        array('codigo_dane'=> '05197', 'nombre'=> 'COCORNA', 'departamento'=> '05'),
        array('codigo_dane'=> '05206', 'nombre'=> 'CONCEPCION', 'departamento'=> '05'),
        array('codigo_dane'=> '05209', 'nombre'=> 'CONCORDIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05212', 'nombre'=> 'COPACABANA', 'departamento'=> '05'),
        array('codigo_dane'=> '05234', 'nombre'=> 'DABEIBA', 'departamento'=> '05'),
        array('codigo_dane'=> '05237', 'nombre'=> 'DON MATIAS', 'departamento'=> '05'),
        array('codigo_dane'=> '05240', 'nombre'=> 'EBEJICO', 'departamento'=> '05'),
        array('codigo_dane'=> '05250', 'nombre'=> 'EL BAGRE', 'departamento'=> '05'),
        array('codigo_dane'=> '05264', 'nombre'=> 'ENTRERRIOS', 'departamento'=> '05'),
        array('codigo_dane'=> '05266', 'nombre'=> 'ENVIGADO', 'departamento'=> '05'),
        array('codigo_dane'=> '05282', 'nombre'=> 'FREDONIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05284', 'nombre'=> 'FRONTINO', 'departamento'=> '05'),
        array('codigo_dane'=> '05306', 'nombre'=> 'GIRALDO', 'departamento'=> '05'),
        array('codigo_dane'=> '05308', 'nombre'=> 'GIRARDOTA', 'departamento'=> '05'),
        array('codigo_dane'=> '05310', 'nombre'=> 'GOMEZ PLATA', 'departamento'=> '05'),
        array('codigo_dane'=> '05313', 'nombre'=> 'GRANADA', 'departamento'=> '05'),
        array('codigo_dane'=> '05315', 'nombre'=> 'GUADALUPE', 'departamento'=> '05'),
        array('codigo_dane'=> '05318', 'nombre'=> 'GUARNE', 'departamento'=> '05'),
        array('codigo_dane'=> '05321', 'nombre'=> 'GUATAPE', 'departamento'=> '05'),
        array('codigo_dane'=> '05347', 'nombre'=> 'HELICONIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05353', 'nombre'=> 'HISPANIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05360', 'nombre'=> 'ITAGUI', 'departamento'=> '05'),
        array('codigo_dane'=> '05361', 'nombre'=> 'ITUANGO', 'departamento'=> '05'),
        array('codigo_dane'=> '05364', 'nombre'=> 'JARDIN', 'departamento'=> '05'),
        array('codigo_dane'=> '05368', 'nombre'=> 'JERICO', 'departamento'=> '05'),
        array('codigo_dane'=> '05376', 'nombre'=> 'LA CEJA', 'departamento'=> '05'),
        array('codigo_dane'=> '05380', 'nombre'=> 'LA ESTRELLA', 'departamento'=> '05'),
        array('codigo_dane'=> '05390', 'nombre'=> 'LA PINTADA', 'departamento'=> '05'),
        array('codigo_dane'=> '05400', 'nombre'=> 'LA UNION', 'departamento'=> '05'),
        array('codigo_dane'=> '05411', 'nombre'=> 'LIBORINA', 'departamento'=> '05'),
        array('codigo_dane'=> '05425', 'nombre'=> 'MACEO', 'departamento'=> '05'),
        array('codigo_dane'=> '05440', 'nombre'=> 'MARINILLA', 'departamento'=> '05'),
        array('codigo_dane'=> '05467', 'nombre'=> 'MONTEBELLO', 'departamento'=> '05'),
        array('codigo_dane'=> '05475', 'nombre'=> 'MURINDO', 'departamento'=> '05'),
        array('codigo_dane'=> '05480', 'nombre'=> 'MUTATA', 'departamento'=> '05'),
        array('codigo_dane'=> '05483', 'nombre'=> 'NARIÑO', 'departamento'=> '05'),
        array('codigo_dane'=> '05490', 'nombre'=> 'NECOCLI', 'departamento'=> '05'),
        array('codigo_dane'=> '05495', 'nombre'=> 'NECHI', 'departamento'=> '05'),
        array('codigo_dane'=> '05501', 'nombre'=> 'OLAYA', 'departamento'=> '05'),
        array('codigo_dane'=> '05541', 'nombre'=> 'PEÐOL', 'departamento'=> '05'),
        array('codigo_dane'=> '05543', 'nombre'=> 'PEQUE', 'departamento'=> '05'),
        array('codigo_dane'=> '05576', 'nombre'=> 'PUEBLORRICO', 'departamento'=> '05'),
        array('codigo_dane'=> '05579', 'nombre'=> 'PUERTO BERRIO', 'departamento'=> '05'),
        array('codigo_dane'=> '05585', 'nombre'=> 'PUERTO NARE', 'departamento'=> '05'),
        array('codigo_dane'=> '05591', 'nombre'=> 'PUERTO TRIUNFO', 'departamento'=> '05'),
        array('codigo_dane'=> '05604', 'nombre'=> 'REMEDIOS', 'departamento'=> '05'),
        array('codigo_dane'=> '05607', 'nombre'=> 'RETIRO', 'departamento'=> '05'),
        array('codigo_dane'=> '05615', 'nombre'=> 'RIONEGRO', 'departamento'=> '05'),
        array('codigo_dane'=> '05628', 'nombre'=> 'SABANALARGA', 'departamento'=> '05'),
        array('codigo_dane'=> '05631', 'nombre'=> 'SABANETA', 'departamento'=> '05'),
        array('codigo_dane'=> '05642', 'nombre'=> 'SALGAR', 'departamento'=> '05'),
        array('codigo_dane'=> '05647', 'nombre'=> 'SAN ANDRES DE CUERQUIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05649', 'nombre'=> 'SAN CARLOS', 'departamento'=> '05'),
        array('codigo_dane'=> '05652', 'nombre'=> 'SAN FRANCISCO', 'departamento'=> '05'),
        array('codigo_dane'=> '05656', 'nombre'=> 'SAN JERONIMO', 'departamento'=> '05'),
        array('codigo_dane'=> '05658', 'nombre'=> 'SAN JOSE DE LA MONTAÑA', 'departamento'=> '05'),
        array('codigo_dane'=> '05659', 'nombre'=> 'SAN JUAN DE URABA', 'departamento'=> '05'),
        array('codigo_dane'=> '05660', 'nombre'=> 'SAN LUIS', 'departamento'=> '05'),
        array('codigo_dane'=> '05664', 'nombre'=> 'SAN PEDRO', 'departamento'=> '05'),
        array('codigo_dane'=> '05665', 'nombre'=> 'SAN PEDRO DE URABA', 'departamento'=> '05'),
        array('codigo_dane'=> '05667', 'nombre'=> 'SAN RAFAEL', 'departamento'=> '05'),
        array('codigo_dane'=> '05670', 'nombre'=> 'SAN ROQUE', 'departamento'=> '05'),
        array('codigo_dane'=> '05674', 'nombre'=> 'SAN VICENTE', 'departamento'=> '05'),
        array('codigo_dane'=> '05679', 'nombre'=> 'SANTA BARBARA', 'departamento'=> '05'),
        array('codigo_dane'=> '05686', 'nombre'=> 'SANTA ROSA DE OSOS', 'departamento'=> '05'),
        array('codigo_dane'=> '05690', 'nombre'=> 'SANTO DOMINGO', 'departamento'=> '05'),
        array('codigo_dane'=> '05697', 'nombre'=> 'EL SANTUARIO', 'departamento'=> '05'),
        array('codigo_dane'=> '05736', 'nombre'=> 'SEGOVIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05756', 'nombre'=> 'SONSON', 'departamento'=> '05'),
        array('codigo_dane'=> '05761', 'nombre'=> 'SOPETRAN', 'departamento'=> '05'),
        array('codigo_dane'=> '05789', 'nombre'=> 'TAMESIS', 'departamento'=> '05'),
        array('codigo_dane'=> '05790', 'nombre'=> 'TARAZA', 'departamento'=> '05'),
        array('codigo_dane'=> '05792', 'nombre'=> 'TARSO', 'departamento'=> '05'),
        array('codigo_dane'=> '05809', 'nombre'=> 'TITIRIBI', 'departamento'=> '05'),
        array('codigo_dane'=> '05819', 'nombre'=> 'TOLEDO', 'departamento'=> '05'),
        array('codigo_dane'=> '05837', 'nombre'=> 'TURBO', 'departamento'=> '05'),
        array('codigo_dane'=> '05842', 'nombre'=> 'URAMITA', 'departamento'=> '05'),
        array('codigo_dane'=> '05847', 'nombre'=> 'URRAO', 'departamento'=> '05'),
        array('codigo_dane'=> '05854', 'nombre'=> 'VALDIVIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05856', 'nombre'=> 'VALPARAISO', 'departamento'=> '05'),
        array('codigo_dane'=> '05858', 'nombre'=> 'VEGACHI', 'departamento'=> '05'),
        array('codigo_dane'=> '05861', 'nombre'=> 'VENECIA', 'departamento'=> '05'),
        array('codigo_dane'=> '05873', 'nombre'=> 'VIGIA DEL FUERTE', 'departamento'=> '05'),
        array('codigo_dane'=> '05885', 'nombre'=> 'YALI', 'departamento'=> '05'),
        array('codigo_dane'=> '05887', 'nombre'=> 'YARUMAL', 'departamento'=> '05'),
        array('codigo_dane'=> '05890', 'nombre'=> 'YOLOMBO', 'departamento'=> '05'),
        array('codigo_dane'=> '05893', 'nombre'=> 'YONDO', 'departamento'=> '05'),
        array('codigo_dane'=> '05895', 'nombre'=> 'ZARAGOZA', 'departamento'=> '05'),
        array('codigo_dane'=> '08001', 'nombre'=> 'BARRANQUILLA', 'departamento'=> '08'),
        array('codigo_dane'=> '08078', 'nombre'=> 'BARANOA', 'departamento'=> '08'),
        array('codigo_dane'=> '08137', 'nombre'=> 'CAMPO DE LA CRUZ', 'departamento'=> '08'),
        array('codigo_dane'=> '08141', 'nombre'=> 'CANDELARIA', 'departamento'=> '08'),
        array('codigo_dane'=> '08296', 'nombre'=> 'GALAPA', 'departamento'=> '08'),
        array('codigo_dane'=> '08372', 'nombre'=> 'JUAN DE ACOSTA', 'departamento'=> '08'),
        array('codigo_dane'=> '08421', 'nombre'=> 'LURUACO', 'departamento'=> '08'),
        array('codigo_dane'=> '08433', 'nombre'=> 'MALAMBO', 'departamento'=> '08'),
        array('codigo_dane'=> '08436', 'nombre'=> 'MANATI', 'departamento'=> '08'),
        array('codigo_dane'=> '08520', 'nombre'=> 'PALMAR DE VARELA', 'departamento'=> '08'),
        array('codigo_dane'=> '08549', 'nombre'=> 'PIOJO', 'departamento'=> '08'),
        array('codigo_dane'=> '08558', 'nombre'=> 'POLONUEVO', 'departamento'=> '08'),
        array('codigo_dane'=> '08560', 'nombre'=> 'PONEDERA', 'departamento'=> '08'),
        array('codigo_dane'=> '08573', 'nombre'=> 'PUERTO COLOMBIA', 'departamento'=> '08'),
        array('codigo_dane'=> '08606', 'nombre'=> 'REPELON', 'departamento'=> '08'),
        array('codigo_dane'=> '08634', 'nombre'=> 'SABANAGRANDE', 'departamento'=> '08'),
        array('codigo_dane'=> '08638', 'nombre'=> 'SABANALARGA', 'departamento'=> '08'),
        array('codigo_dane'=> '08675', 'nombre'=> 'SANTA LUCIA', 'departamento'=> '08'),
        array('codigo_dane'=> '08685', 'nombre'=> 'SANTO TOMAS', 'departamento'=> '08'),
        array('codigo_dane'=> '08758', 'nombre'=> 'SOLEDAD', 'departamento'=> '08'),
        array('codigo_dane'=> '08770', 'nombre'=> 'SUAN', 'departamento'=> '08'),
        array('codigo_dane'=> '08832', 'nombre'=> 'TUBARA', 'departamento'=> '08'),
        array('codigo_dane'=> '08849', 'nombre'=> 'USIACURI', 'departamento'=> '08'),
        array('codigo_dane'=> '11001', 'nombre'=> 'BOGOTA, D.C.', 'departamento'=> '11'),
        array('codigo_dane'=> '13001', 'nombre'=> 'CARTAGENA', 'departamento'=> '13'),
        array('codigo_dane'=> '13006', 'nombre'=> 'ACHI', 'departamento'=> '13'),
        array('codigo_dane'=> '13030', 'nombre'=> 'ALTOS DEL ROSARIO', 'departamento'=> '13'),
        array('codigo_dane'=> '13042', 'nombre'=> 'ARENAL', 'departamento'=> '13'),
        array('codigo_dane'=> '13052', 'nombre'=> 'ARJONA', 'departamento'=> '13'),
        array('codigo_dane'=> '13062', 'nombre'=> 'ARROYOHONDO', 'departamento'=> '13'),
        array('codigo_dane'=> '13074', 'nombre'=> 'BARRANCO DE LOBA', 'departamento'=> '13'),
        array('codigo_dane'=> '13140', 'nombre'=> 'CALAMAR', 'departamento'=> '13'),
        array('codigo_dane'=> '13160', 'nombre'=> 'CANTAGALLO', 'departamento'=> '13'),
        array('codigo_dane'=> '13188', 'nombre'=> 'CICUCO', 'departamento'=> '13'),
        array('codigo_dane'=> '13212', 'nombre'=> 'CORDOBA', 'departamento'=> '13'),
        array('codigo_dane'=> '13222', 'nombre'=> 'CLEMENCIA', 'departamento'=> '13'),
        array('codigo_dane'=> '13244', 'nombre'=> 'EL CARMEN DE BOLIVAR', 'departamento'=> '13'),
        array('codigo_dane'=> '13248', 'nombre'=> 'EL GUAMO', 'departamento'=> '13'),
        array('codigo_dane'=> '13268', 'nombre'=> 'EL PEÑON', 'departamento'=> '13'),
        array('codigo_dane'=> '13300', 'nombre'=> 'HATILLO DE LOBA', 'departamento'=> '13'),
        array('codigo_dane'=> '13430', 'nombre'=> 'MAGANGUE', 'departamento'=> '13'),
        array('codigo_dane'=> '13433', 'nombre'=> 'MAHATES', 'departamento'=> '13'),
        array('codigo_dane'=> '13440', 'nombre'=> 'MARGARITA', 'departamento'=> '13'),
        array('codigo_dane'=> '13442', 'nombre'=> 'MARIA LA BAJA', 'departamento'=> '13'),
        array('codigo_dane'=> '13458', 'nombre'=> 'MONTECRISTO', 'departamento'=> '13'),
        array('codigo_dane'=> '13468', 'nombre'=> 'MOMPOS', 'departamento'=> '13'),
        array('codigo_dane'=> '13490', 'nombre'=> 'NOROSI', 'departamento'=> '13'),
        array('codigo_dane'=> '13473', 'nombre'=> 'MORALES', 'departamento'=> '13'),
        array('codigo_dane'=> '13549', 'nombre'=> 'PINILLOS', 'departamento'=> '13'),
        array('codigo_dane'=> '13580', 'nombre'=> 'REGIDOR', 'departamento'=> '13'),
        array('codigo_dane'=> '13600', 'nombre'=> 'RIO VIEJO', 'departamento'=> '13'),
        array('codigo_dane'=> '13620', 'nombre'=> 'SAN CRISTOBAL', 'departamento'=> '13'),
        array('codigo_dane'=> '13647', 'nombre'=> 'SAN ESTANISLAO', 'departamento'=> '13'),
        array('codigo_dane'=> '13650', 'nombre'=> 'SAN FERNANDO', 'departamento'=> '13'),
        array('codigo_dane'=> '13654', 'nombre'=> 'SAN JACINTO', 'departamento'=> '13'),
        array('codigo_dane'=> '13655', 'nombre'=> 'SAN JACINTO DEL CAUCA', 'departamento'=> '13'),
        array('codigo_dane'=> '13657', 'nombre'=> 'SAN JUAN NEPOMUCENO', 'departamento'=> '13'),
        array('codigo_dane'=> '13667', 'nombre'=> 'SAN MARTIN DE LOBA', 'departamento'=> '13'),
        array('codigo_dane'=> '13670', 'nombre'=> 'SAN PABLO', 'departamento'=> '13'),
        array('codigo_dane'=> '13673', 'nombre'=> 'SANTA CATALINA', 'departamento'=> '13'),
        array('codigo_dane'=> '13683', 'nombre'=> 'SANTA ROSA', 'departamento'=> '13'),
        array('codigo_dane'=> '13688', 'nombre'=> 'SANTA ROSA DEL SUR', 'departamento'=> '13'),
        array('codigo_dane'=> '13744', 'nombre'=> 'SIMITI', 'departamento'=> '13'),
        array('codigo_dane'=> '13760', 'nombre'=> 'SOPLAVIENTO', 'departamento'=> '13'),
        array('codigo_dane'=> '13780', 'nombre'=> 'TALAIGUA NUEVO', 'departamento'=> '13'),
        array('codigo_dane'=> '13810', 'nombre'=> 'TIQUISIO', 'departamento'=> '13'),
        array('codigo_dane'=> '13836', 'nombre'=> 'TURBACO', 'departamento'=> '13'),
        array('codigo_dane'=> '13838', 'nombre'=> 'TURBANA', 'departamento'=> '13'),
        array('codigo_dane'=> '13873', 'nombre'=> 'VILLANUEVA', 'departamento'=> '13'),
        array('codigo_dane'=> '13894', 'nombre'=> 'ZAMBRANO', 'departamento'=> '13'),
        array('codigo_dane'=> '15001', 'nombre'=> 'TUNJA', 'departamento'=> '15'),
        array('codigo_dane'=> '15022', 'nombre'=> 'ALMEIDA', 'departamento'=> '15'),
        array('codigo_dane'=> '15047', 'nombre'=> 'AQUITANIA', 'departamento'=> '15'),
        array('codigo_dane'=> '15051', 'nombre'=> 'ARCABUCO', 'departamento'=> '15'),
        array('codigo_dane'=> '15087', 'nombre'=> 'BELEN', 'departamento'=> '15'),
        array('codigo_dane'=> '15090', 'nombre'=> 'BERBEO', 'departamento'=> '15'),
        array('codigo_dane'=> '15092', 'nombre'=> 'BETEITIVA', 'departamento'=> '15'),
        array('codigo_dane'=> '15097', 'nombre'=> 'BOAVITA', 'departamento'=> '15'),
        array('codigo_dane'=> '15104', 'nombre'=> 'BOYACA', 'departamento'=> '15'),
        array('codigo_dane'=> '15106', 'nombre'=> 'BRICEÑO', 'departamento'=> '15'),
        array('codigo_dane'=> '15109', 'nombre'=> 'BUENAVISTA', 'departamento'=> '15'),
        array('codigo_dane'=> '15114', 'nombre'=> 'BUSBANZA', 'departamento'=> '15'),
        array('codigo_dane'=> '15131', 'nombre'=> 'CALDAS', 'departamento'=> '15'),
        array('codigo_dane'=> '15135', 'nombre'=> 'CAMPOHERMOSO', 'departamento'=> '15'),
        array('codigo_dane'=> '15162', 'nombre'=> 'CERINZA', 'departamento'=> '15'),
        array('codigo_dane'=> '15172', 'nombre'=> 'CHINAVITA', 'departamento'=> '15'),
        array('codigo_dane'=> '15176', 'nombre'=> 'CHIQUINQUIRA', 'departamento'=> '15'),
        array('codigo_dane'=> '15180', 'nombre'=> 'CHISCAS', 'departamento'=> '15'),
        array('codigo_dane'=> '15183', 'nombre'=> 'CHITA', 'departamento'=> '15'),
        array('codigo_dane'=> '15185', 'nombre'=> 'CHITARAQUE', 'departamento'=> '15'),
        array('codigo_dane'=> '15187', 'nombre'=> 'CHIVATA', 'departamento'=> '15'),
        array('codigo_dane'=> '15189', 'nombre'=> 'CIENEGA', 'departamento'=> '15'),
        array('codigo_dane'=> '15204', 'nombre'=> 'COMBITA', 'departamento'=> '15'),
        array('codigo_dane'=> '15212', 'nombre'=> 'COPER', 'departamento'=> '15'),
        array('codigo_dane'=> '15215', 'nombre'=> 'CORRALES', 'departamento'=> '15'),
        array('codigo_dane'=> '15218', 'nombre'=> 'COVARACHIA', 'departamento'=> '15'),
        array('codigo_dane'=> '15223', 'nombre'=> 'CUBARA', 'departamento'=> '15'),
        array('codigo_dane'=> '15224', 'nombre'=> 'CUCAITA', 'departamento'=> '15'),
        array('codigo_dane'=> '15226', 'nombre'=> 'CUITIVA', 'departamento'=> '15'),
        array('codigo_dane'=> '15232', 'nombre'=> 'CHIQUIZA', 'departamento'=> '15'),
        array('codigo_dane'=> '15236', 'nombre'=> 'CHIVOR', 'departamento'=> '15'),
        array('codigo_dane'=> '15238', 'nombre'=> 'DUITAMA', 'departamento'=> '15'),
        array('codigo_dane'=> '15244', 'nombre'=> 'EL COCUY', 'departamento'=> '15'),
        array('codigo_dane'=> '15248', 'nombre'=> 'EL ESPINO', 'departamento'=> '15'),
        array('codigo_dane'=> '15272', 'nombre'=> 'FIRAVITOBA', 'departamento'=> '15'),
        array('codigo_dane'=> '15276', 'nombre'=> 'FLORESTA', 'departamento'=> '15'),
        array('codigo_dane'=> '15293', 'nombre'=> 'GACHANTIVA', 'departamento'=> '15'),
        array('codigo_dane'=> '15296', 'nombre'=> 'GAMEZA', 'departamento'=> '15'),
        array('codigo_dane'=> '15299', 'nombre'=> 'GARAGOA', 'departamento'=> '15'),
        array('codigo_dane'=> '15317', 'nombre'=> 'GUACAMAYAS', 'departamento'=> '15'),
        array('codigo_dane'=> '15322', 'nombre'=> 'GUATEQUE', 'departamento'=> '15'),
        array('codigo_dane'=> '15325', 'nombre'=> 'GUAYATA', 'departamento'=> '15'),
        array('codigo_dane'=> '15332', 'nombre'=> 'GsICAN', 'departamento'=> '15'),
        array('codigo_dane'=> '15362', 'nombre'=> 'IZA', 'departamento'=> '15'),
        array('codigo_dane'=> '15367', 'nombre'=> 'JENESANO', 'departamento'=> '15'),
        array('codigo_dane'=> '15368', 'nombre'=> 'JERICO', 'departamento'=> '15'),
        array('codigo_dane'=> '15377', 'nombre'=> 'LABRANZAGRANDE', 'departamento'=> '15'),
        array('codigo_dane'=> '15380', 'nombre'=> 'LA CAPILLA', 'departamento'=> '15'),
        array('codigo_dane'=> '15401', 'nombre'=> 'LA VICTORIA', 'departamento'=> '15'),
        array('codigo_dane'=> '15403', 'nombre'=> 'LA UVITA', 'departamento'=> '15'),
        array('codigo_dane'=> '15407', 'nombre'=> 'VILLA DE LEYVA', 'departamento'=> '15'),
        array('codigo_dane'=> '15425', 'nombre'=> 'MACANAL', 'departamento'=> '15'),
        array('codigo_dane'=> '15442', 'nombre'=> 'MARIPI', 'departamento'=> '15'),
        array('codigo_dane'=> '15455', 'nombre'=> 'MIRAFLORES', 'departamento'=> '15'),
        array('codigo_dane'=> '15464', 'nombre'=> 'MONGUA', 'departamento'=> '15'),
        array('codigo_dane'=> '15466', 'nombre'=> 'MONGUI', 'departamento'=> '15'),
        array('codigo_dane'=> '15469', 'nombre'=> 'MONIQUIRA', 'departamento'=> '15'),
        array('codigo_dane'=> '15476', 'nombre'=> 'MOTAVITA', 'departamento'=> '15'),
        array('codigo_dane'=> '15480', 'nombre'=> 'MUZO', 'departamento'=> '15'),
        array('codigo_dane'=> '15491', 'nombre'=> 'NOBSA', 'departamento'=> '15'),
        array('codigo_dane'=> '15494', 'nombre'=> 'NUEVO COLON', 'departamento'=> '15'),
        array('codigo_dane'=> '15500', 'nombre'=> 'OICATA', 'departamento'=> '15'),
        array('codigo_dane'=> '15507', 'nombre'=> 'OTANCHE', 'departamento'=> '15'),
        array('codigo_dane'=> '15511', 'nombre'=> 'PACHAVITA', 'departamento'=> '15'),
        array('codigo_dane'=> '15514', 'nombre'=> 'PAEZ', 'departamento'=> '15'),
        array('codigo_dane'=> '15516', 'nombre'=> 'PAIPA', 'departamento'=> '15'),
        array('codigo_dane'=> '15518', 'nombre'=> 'PAJARITO', 'departamento'=> '15'),
        array('codigo_dane'=> '15522', 'nombre'=> 'PANQUEBA', 'departamento'=> '15'),
        array('codigo_dane'=> '15531', 'nombre'=> 'PAUNA', 'departamento'=> '15'),
        array('codigo_dane'=> '15533', 'nombre'=> 'PAYA', 'departamento'=> '15'),
        array('codigo_dane'=> '15537', 'nombre'=> 'PAZ DE RIO', 'departamento'=> '15'),
        array('codigo_dane'=> '15542', 'nombre'=> 'PESCA', 'departamento'=> '15'),
        array('codigo_dane'=> '15550', 'nombre'=> 'PISBA', 'departamento'=> '15'),
        array('codigo_dane'=> '15572', 'nombre'=> 'PUERTO BOYACA', 'departamento'=> '15'),
        array('codigo_dane'=> '15580', 'nombre'=> 'QUIPAMA', 'departamento'=> '15'),
        array('codigo_dane'=> '15599', 'nombre'=> 'RAMIRIQUI', 'departamento'=> '15'),
        array('codigo_dane'=> '15600', 'nombre'=> 'RAQUIRA', 'departamento'=> '15'),
        array('codigo_dane'=> '15621', 'nombre'=> 'RONDON', 'departamento'=> '15'),
        array('codigo_dane'=> '15632', 'nombre'=> 'SABOYA', 'departamento'=> '15'),
        array('codigo_dane'=> '15638', 'nombre'=> 'SACHICA', 'departamento'=> '15'),
        array('codigo_dane'=> '15646', 'nombre'=> 'SAMACA', 'departamento'=> '15'),
        array('codigo_dane'=> '15660', 'nombre'=> 'SAN EDUARDO', 'departamento'=> '15'),
        array('codigo_dane'=> '15664', 'nombre'=> 'SAN JOSE DE PARE', 'departamento'=> '15'),
        array('codigo_dane'=> '15667', 'nombre'=> 'SAN LUIS DE GACENO', 'departamento'=> '15'),
        array('codigo_dane'=> '15673', 'nombre'=> 'SAN MATEO', 'departamento'=> '15'),
        array('codigo_dane'=> '15676', 'nombre'=> 'SAN MIGUEL DE SEMA', 'departamento'=> '15'),
        array('codigo_dane'=> '15681', 'nombre'=> 'SAN PABLO DE BORBUR', 'departamento'=> '15'),
        array('codigo_dane'=> '15686', 'nombre'=> 'SANTANA', 'departamento'=> '15'),
        array('codigo_dane'=> '15690', 'nombre'=> 'SANTA MARIA', 'departamento'=> '15'),
        array('codigo_dane'=> '15693', 'nombre'=> 'SANTA ROSA DE VITERBO', 'departamento'=> '15'),
        array('codigo_dane'=> '15696', 'nombre'=> 'SANTA SOFIA', 'departamento'=> '15'),
        array('codigo_dane'=> '15720', 'nombre'=> 'SATIVANORTE', 'departamento'=> '15'),
        array('codigo_dane'=> '15723', 'nombre'=> 'SATIVASUR', 'departamento'=> '15'),
        array('codigo_dane'=> '15740', 'nombre'=> 'SIACHOQUE', 'departamento'=> '15'),
        array('codigo_dane'=> '15753', 'nombre'=> 'SOATA', 'departamento'=> '15'),
        array('codigo_dane'=> '15755', 'nombre'=> 'SOCOTA', 'departamento'=> '15'),
        array('codigo_dane'=> '15757', 'nombre'=> 'SOCHA', 'departamento'=> '15'),
        array('codigo_dane'=> '15759', 'nombre'=> 'SOGAMOSO', 'departamento'=> '15'),
        array('codigo_dane'=> '15761', 'nombre'=> 'SOMONDOCO', 'departamento'=> '15'),
        array('codigo_dane'=> '15762', 'nombre'=> 'SORA', 'departamento'=> '15'),
        array('codigo_dane'=> '15763', 'nombre'=> 'SOTAQUIRA', 'departamento'=> '15'),
        array('codigo_dane'=> '15764', 'nombre'=> 'SORACA', 'departamento'=> '15'),
        array('codigo_dane'=> '15774', 'nombre'=> 'SUSACON', 'departamento'=> '15'),
        array('codigo_dane'=> '15776', 'nombre'=> 'SUTAMARCHAN', 'departamento'=> '15'),
        array('codigo_dane'=> '15778', 'nombre'=> 'SUTATENZA', 'departamento'=> '15'),
        array('codigo_dane'=> '15790', 'nombre'=> 'TASCO', 'departamento'=> '15'),
        array('codigo_dane'=> '15798', 'nombre'=> 'TENZA', 'departamento'=> '15'),
        array('codigo_dane'=> '15804', 'nombre'=> 'TIBANA', 'departamento'=> '15'),
        array('codigo_dane'=> '15806', 'nombre'=> 'TIBASOSA', 'departamento'=> '15'),
        array('codigo_dane'=> '15808', 'nombre'=> 'TINJACA', 'departamento'=> '15'),
        array('codigo_dane'=> '15810', 'nombre'=> 'TIPACOQUE', 'departamento'=> '15'),
        array('codigo_dane'=> '15814', 'nombre'=> 'TOCA', 'departamento'=> '15'),
        array('codigo_dane'=> '15816', 'nombre'=> 'TOGsI', 'departamento'=> '15'),
        array('codigo_dane'=> '15820', 'nombre'=> 'TOPAGA', 'departamento'=> '15'),
        array('codigo_dane'=> '15822', 'nombre'=> 'TOTA', 'departamento'=> '15'),
        array('codigo_dane'=> '15832', 'nombre'=> 'TUNUNGUA', 'departamento'=> '15'),
        array('codigo_dane'=> '15835', 'nombre'=> 'TURMEQUE', 'departamento'=> '15'),
        array('codigo_dane'=> '15837', 'nombre'=> 'TUTA', 'departamento'=> '15'),
        array('codigo_dane'=> '15839', 'nombre'=> 'TUTAZA', 'departamento'=> '15'),
        array('codigo_dane'=> '15842', 'nombre'=> 'UMBITA', 'departamento'=> '15'),
        array('codigo_dane'=> '15861', 'nombre'=> 'VENTAQUEMADA', 'departamento'=> '15'),
        array('codigo_dane'=> '15879', 'nombre'=> 'VIRACACHA', 'departamento'=> '15'),
        array('codigo_dane'=> '15897', 'nombre'=> 'ZETAQUIRA', 'departamento'=> '15'),
        array('codigo_dane'=> '17001', 'nombre'=> 'MANIZALES', 'departamento'=> '17'),
        array('codigo_dane'=> '17013', 'nombre'=> 'AGUADAS', 'departamento'=> '17'),
        array('codigo_dane'=> '17042', 'nombre'=> 'ANSERMA', 'departamento'=> '17'),
        array('codigo_dane'=> '17050', 'nombre'=> 'ARANZAZU', 'departamento'=> '17'),
        array('codigo_dane'=> '17088', 'nombre'=> 'BELALCAZAR', 'departamento'=> '17'),
        array('codigo_dane'=> '17174', 'nombre'=> 'CHINCHINA', 'departamento'=> '17'),
        array('codigo_dane'=> '17272', 'nombre'=> 'FILADELFIA', 'departamento'=> '17'),
        array('codigo_dane'=> '17380', 'nombre'=> 'LA DORADA', 'departamento'=> '17'),
        array('codigo_dane'=> '17388', 'nombre'=> 'LA MERCED', 'departamento'=> '17'),
        array('codigo_dane'=> '17433', 'nombre'=> 'MANZANARES', 'departamento'=> '17'),
        array('codigo_dane'=> '17442', 'nombre'=> 'MARMATO', 'departamento'=> '17'),
        array('codigo_dane'=> '17444', 'nombre'=> 'MARQUETALIA', 'departamento'=> '17'),
        array('codigo_dane'=> '17446', 'nombre'=> 'MARULANDA', 'departamento'=> '17'),
        array('codigo_dane'=> '17486', 'nombre'=> 'NEIRA', 'departamento'=> '17'),
        array('codigo_dane'=> '17495', 'nombre'=> 'NORCASIA', 'departamento'=> '17'),
        array('codigo_dane'=> '17513', 'nombre'=> 'PACORA', 'departamento'=> '17'),
        array('codigo_dane'=> '17524', 'nombre'=> 'PALESTINA', 'departamento'=> '17'),
        array('codigo_dane'=> '17541', 'nombre'=> 'PENSILVANIA', 'departamento'=> '17'),
        array('codigo_dane'=> '17614', 'nombre'=> 'RIOSUCIO', 'departamento'=> '17'),
        array('codigo_dane'=> '17616', 'nombre'=> 'RISARALDA', 'departamento'=> '17'),
        array('codigo_dane'=> '17653', 'nombre'=> 'SALAMINA', 'departamento'=> '17'),
        array('codigo_dane'=> '17662', 'nombre'=> 'SAMANA', 'departamento'=> '17'),
        array('codigo_dane'=> '17665', 'nombre'=> 'SAN JOSE', 'departamento'=> '17'),
        array('codigo_dane'=> '17777', 'nombre'=> 'SUPIA', 'departamento'=> '17'),
        array('codigo_dane'=> '17867', 'nombre'=> 'VICTORIA', 'departamento'=> '17'),
        array('codigo_dane'=> '17873', 'nombre'=> 'VILLAMARIA', 'departamento'=> '17'),
        array('codigo_dane'=> '17877', 'nombre'=> 'VITERBO', 'departamento'=> '17'),
        array('codigo_dane'=> '18001', 'nombre'=> 'FLORENCIA', 'departamento'=> '18'),
        array('codigo_dane'=> '18029', 'nombre'=> 'ALBANIA', 'departamento'=> '18'),
        array('codigo_dane'=> '18094', 'nombre'=> 'BELEN DE LOS ANDAQUIES', 'departamento'=> '18'),
        array('codigo_dane'=> '18150', 'nombre'=> 'CARTAGENA DEL CHAIRA', 'departamento'=> '18'),
        array('codigo_dane'=> '18205', 'nombre'=> 'CURILLO', 'departamento'=> '18'),
        array('codigo_dane'=> '18247', 'nombre'=> 'EL DONCELLO', 'departamento'=> '18'),
        array('codigo_dane'=> '18256', 'nombre'=> 'EL PAUJIL', 'departamento'=> '18'),
        array('codigo_dane'=> '18410', 'nombre'=> 'LA MONTAÑITA', 'departamento'=> '18'),
        array('codigo_dane'=> '18460', 'nombre'=> 'MILAN', 'departamento'=> '18'),
        array('codigo_dane'=> '18479', 'nombre'=> 'MORELIA', 'departamento'=> '18'),
        array('codigo_dane'=> '18592', 'nombre'=> 'PUERTO RICO', 'departamento'=> '18'),
        array('codigo_dane'=> '18610', 'nombre'=> 'SAN JOSE DEL FRAGUA', 'departamento'=> '18'),
        array('codigo_dane'=> '18753', 'nombre'=> 'SAN VICENTE DEL CAGUAN', 'departamento'=> '18'),
        array('codigo_dane'=> '18756', 'nombre'=> 'SOLANO', 'departamento'=> '18'),
        array('codigo_dane'=> '18785', 'nombre'=> 'SOLITA', 'departamento'=> '18'),
        array('codigo_dane'=> '18860', 'nombre'=> 'VALPARAISO', 'departamento'=> '18'),
        array('codigo_dane'=> '19001', 'nombre'=> 'POPAYAN', 'departamento'=> '19'),
        array('codigo_dane'=> '19022', 'nombre'=> 'ALMAGUER', 'departamento'=> '19'),
        array('codigo_dane'=> '19050', 'nombre'=> 'ARGELIA', 'departamento'=> '19'),
        array('codigo_dane'=> '19075', 'nombre'=> 'BALBOA', 'departamento'=> '19'),
        array('codigo_dane'=> '19100', 'nombre'=> 'BOLIVAR', 'departamento'=> '19'),
        array('codigo_dane'=> '19110', 'nombre'=> 'BUENOS AIRES', 'departamento'=> '19'),
        array('codigo_dane'=> '19130', 'nombre'=> 'CAJIBIO', 'departamento'=> '19'),
        array('codigo_dane'=> '19137', 'nombre'=> 'CALDONO', 'departamento'=> '19'),
        array('codigo_dane'=> '19142', 'nombre'=> 'CALOTO', 'departamento'=> '19'),
        array('codigo_dane'=> '19212', 'nombre'=> 'CORINTO', 'departamento'=> '19'),
        array('codigo_dane'=> '19256', 'nombre'=> 'EL TAMBO', 'departamento'=> '19'),
        array('codigo_dane'=> '19290', 'nombre'=> 'FLORENCIA', 'departamento'=> '19'),
        array('codigo_dane'=> '19300', 'nombre'=> 'GUACHENE', 'departamento'=> '19'),
        array('codigo_dane'=> '19318', 'nombre'=> 'GUAPI', 'departamento'=> '19'),
        array('codigo_dane'=> '19355', 'nombre'=> 'INZA', 'departamento'=> '19'),
        array('codigo_dane'=> '19364', 'nombre'=> 'JAMBALO', 'departamento'=> '19'),
        array('codigo_dane'=> '19392', 'nombre'=> 'LA SIERRA', 'departamento'=> '19'),
        array('codigo_dane'=> '19397', 'nombre'=> 'LA VEGA', 'departamento'=> '19'),
        array('codigo_dane'=> '19418', 'nombre'=> 'LOPEZ', 'departamento'=> '19'),
        array('codigo_dane'=> '19450', 'nombre'=> 'MERCADERES', 'departamento'=> '19'),
        array('codigo_dane'=> '19455', 'nombre'=> 'MIRANDA', 'departamento'=> '19'),
        array('codigo_dane'=> '19473', 'nombre'=> 'MORALES', 'departamento'=> '19'),
        array('codigo_dane'=> '19513', 'nombre'=> 'PADILLA', 'departamento'=> '19'),
        array('codigo_dane'=> '19517', 'nombre'=> 'PAEZ', 'departamento'=> '19'),
        array('codigo_dane'=> '19532', 'nombre'=> 'PATIA', 'departamento'=> '19'),
        array('codigo_dane'=> '19533', 'nombre'=> 'PIAMONTE', 'departamento'=> '19'),
        array('codigo_dane'=> '19548', 'nombre'=> 'PIENDAMO', 'departamento'=> '19'),
        array('codigo_dane'=> '19573', 'nombre'=> 'PUERTO TEJADA', 'departamento'=> '19'),
        array('codigo_dane'=> '19585', 'nombre'=> 'PURACE', 'departamento'=> '19'),
        array('codigo_dane'=> '19622', 'nombre'=> 'ROSAS', 'departamento'=> '19'),
        array('codigo_dane'=> '19693', 'nombre'=> 'SAN SEBASTIAN', 'departamento'=> '19'),
        array('codigo_dane'=> '19698', 'nombre'=> 'SANTANDER DE QUILICHAO', 'departamento'=> '19'),
        array('codigo_dane'=> '19701', 'nombre'=> 'SANTA ROSA', 'departamento'=> '19'),
        array('codigo_dane'=> '19743', 'nombre'=> 'SILVIA', 'departamento'=> '19'),
        array('codigo_dane'=> '19760', 'nombre'=> 'SOTARA', 'departamento'=> '19'),
        array('codigo_dane'=> '19780', 'nombre'=> 'SUAREZ', 'departamento'=> '19'),
        array('codigo_dane'=> '19785', 'nombre'=> 'SUCRE', 'departamento'=> '19'),
        array('codigo_dane'=> '19807', 'nombre'=> 'TIMBIO', 'departamento'=> '19'),
        array('codigo_dane'=> '19809', 'nombre'=> 'TIMBIQUI', 'departamento'=> '19'),
        array('codigo_dane'=> '19821', 'nombre'=> 'TORIBIO', 'departamento'=> '19'),
        array('codigo_dane'=> '19824', 'nombre'=> 'TOTORO', 'departamento'=> '19'),
        array('codigo_dane'=> '19845', 'nombre'=> 'VILLA RICA', 'departamento'=> '19'),
        array('codigo_dane'=> '20001', 'nombre'=> 'VALLEDUPAR', 'departamento'=> '20'),
        array('codigo_dane'=> '20011', 'nombre'=> 'AGUACHICA', 'departamento'=> '20'),
        array('codigo_dane'=> '20013', 'nombre'=> 'AGUSTIN CODAZZI', 'departamento'=> '20'),
        array('codigo_dane'=> '20032', 'nombre'=> 'ASTREA', 'departamento'=> '20'),
        array('codigo_dane'=> '20045', 'nombre'=> 'BECERRIL', 'departamento'=> '20'),
        array('codigo_dane'=> '20060', 'nombre'=> 'BOSCONIA', 'departamento'=> '20'),
        array('codigo_dane'=> '20175', 'nombre'=> 'CHIMICHAGUA', 'departamento'=> '20'),
        array('codigo_dane'=> '20178', 'nombre'=> 'CHIRIGUANA', 'departamento'=> '20'),
        array('codigo_dane'=> '20228', 'nombre'=> 'CURUMANI', 'departamento'=> '20'),
        array('codigo_dane'=> '20238', 'nombre'=> 'EL COPEY', 'departamento'=> '20'),
        array('codigo_dane'=> '20250', 'nombre'=> 'EL PASO', 'departamento'=> '20'),
        array('codigo_dane'=> '20295', 'nombre'=> 'GAMARRA', 'departamento'=> '20'),
        array('codigo_dane'=> '20310', 'nombre'=> 'GONZALEZ', 'departamento'=> '20'),
        array('codigo_dane'=> '20383', 'nombre'=> 'LA GLORIA', 'departamento'=> '20'),
        array('codigo_dane'=> '20400', 'nombre'=> 'LA JAGUA DE IBIRICO', 'departamento'=> '20'),
        array('codigo_dane'=> '20443', 'nombre'=> 'MANAURE', 'departamento'=> '20'),
        array('codigo_dane'=> '20517', 'nombre'=> 'PAILITAS', 'departamento'=> '20'),
        array('codigo_dane'=> '20550', 'nombre'=> 'PELAYA', 'departamento'=> '20'),
        array('codigo_dane'=> '20570', 'nombre'=> 'PUEBLO BELLO', 'departamento'=> '20'),
        array('codigo_dane'=> '20614', 'nombre'=> 'RIO DE ORO', 'departamento'=> '20'),
        array('codigo_dane'=> '20621', 'nombre'=> 'LA PAZ', 'departamento'=> '20'),
        array('codigo_dane'=> '20710', 'nombre'=> 'SAN ALBERTO', 'departamento'=> '20'),
        array('codigo_dane'=> '20750', 'nombre'=> 'SAN DIEGO', 'departamento'=> '20'),
        array('codigo_dane'=> '20770', 'nombre'=> 'SAN MARTIN', 'departamento'=> '20'),
        array('codigo_dane'=> '20787', 'nombre'=> 'TAMALAMEQUE', 'departamento'=> '20'),
        array('codigo_dane'=> '23001', 'nombre'=> 'MONTERIA', 'departamento'=> '23'),
        array('codigo_dane'=> '23068', 'nombre'=> 'AYAPEL', 'departamento'=> '23'),
        array('codigo_dane'=> '23079', 'nombre'=> 'BUENAVISTA', 'departamento'=> '23'),
        array('codigo_dane'=> '23090', 'nombre'=> 'CANALETE', 'departamento'=> '23'),
        array('codigo_dane'=> '23162', 'nombre'=> 'CERETE', 'departamento'=> '23'),
        array('codigo_dane'=> '23168', 'nombre'=> 'CHIMA', 'departamento'=> '23'),
        array('codigo_dane'=> '23182', 'nombre'=> 'CHINU', 'departamento'=> '23'),
        array('codigo_dane'=> '23189', 'nombre'=> 'CIENAGA DE ORO', 'departamento'=> '23'),
        array('codigo_dane'=> '23300', 'nombre'=> 'COTORRA', 'departamento'=> '23'),
        array('codigo_dane'=> '23350', 'nombre'=> 'LA APARTADA', 'departamento'=> '23'),
        array('codigo_dane'=> '23417', 'nombre'=> 'LORICA', 'departamento'=> '23'),
        array('codigo_dane'=> '23419', 'nombre'=> 'LOS CORDOBAS', 'departamento'=> '23'),
        array('codigo_dane'=> '23464', 'nombre'=> 'MOMIL', 'departamento'=> '23'),
        array('codigo_dane'=> '23466', 'nombre'=> 'MONTELIBANO', 'departamento'=> '23'),
        array('codigo_dane'=> '23500', 'nombre'=> 'MOÑITOS', 'departamento'=> '23'),
        array('codigo_dane'=> '23555', 'nombre'=> 'PLANETA RICA', 'departamento'=> '23'),
        array('codigo_dane'=> '23570', 'nombre'=> 'PUEBLO NUEVO', 'departamento'=> '23'),
        array('codigo_dane'=> '23574', 'nombre'=> 'PUERTO ESCONDIDO', 'departamento'=> '23'),
        array('codigo_dane'=> '23580', 'nombre'=> 'PUERTO LIBERTADOR', 'departamento'=> '23'),
        array('codigo_dane'=> '23586', 'nombre'=> 'PURISIMA', 'departamento'=> '23'),
        array('codigo_dane'=> '23660', 'nombre'=> 'SAHAGUN', 'departamento'=> '23'),
        array('codigo_dane'=> '23670', 'nombre'=> 'SAN ANDRES SOTAVENTO', 'departamento'=> '23'),
        array('codigo_dane'=> '23672', 'nombre'=> 'SAN ANTERO', 'departamento'=> '23'),
        array('codigo_dane'=> '23675', 'nombre'=> 'SAN BERNARDO DEL VIENTO', 'departamento'=> '23'),
        array('codigo_dane'=> '23678', 'nombre'=> 'SAN CARLOS', 'departamento'=> '23'),
        array('codigo_dane'=> '23686', 'nombre'=> 'SAN PELAYO', 'departamento'=> '23'),
        array('codigo_dane'=> '23807', 'nombre'=> 'TIERRALTA', 'departamento'=> '23'),
        array('codigo_dane'=> '23855', 'nombre'=> 'VALENCIA', 'departamento'=> '23'),
        array('codigo_dane'=> '25001', 'nombre'=> 'AGUA DE DIOS', 'departamento'=> '25'),
        array('codigo_dane'=> '25019', 'nombre'=> 'ALBAN', 'departamento'=> '25'),
        array('codigo_dane'=> '25035', 'nombre'=> 'ANAPOIMA', 'departamento'=> '25'),
        array('codigo_dane'=> '25040', 'nombre'=> 'ANOLAIMA', 'departamento'=> '25'),
        array('codigo_dane'=> '25053', 'nombre'=> 'ARBELAEZ', 'departamento'=> '25'),
        array('codigo_dane'=> '25086', 'nombre'=> 'BELTRAN', 'departamento'=> '25'),
        array('codigo_dane'=> '25095', 'nombre'=> 'BITUIMA', 'departamento'=> '25'),
        array('codigo_dane'=> '25099', 'nombre'=> 'BOJACA', 'departamento'=> '25'),
        array('codigo_dane'=> '25120', 'nombre'=> 'CABRERA', 'departamento'=> '25'),
        array('codigo_dane'=> '25123', 'nombre'=> 'CACHIPAY', 'departamento'=> '25'),
        array('codigo_dane'=> '25126', 'nombre'=> 'CAJICA', 'departamento'=> '25'),
        array('codigo_dane'=> '25148', 'nombre'=> 'CAPARRAPI', 'departamento'=> '25'),
        array('codigo_dane'=> '25151', 'nombre'=> 'CAQUEZA', 'departamento'=> '25'),
        array('codigo_dane'=> '25154', 'nombre'=> 'CARMEN DE CARUPA', 'departamento'=> '25'),
        array('codigo_dane'=> '25168', 'nombre'=> 'CHAGUANI', 'departamento'=> '25'),
        array('codigo_dane'=> '25175', 'nombre'=> 'CHIA', 'departamento'=> '25'),
        array('codigo_dane'=> '25178', 'nombre'=> 'CHIPAQUE', 'departamento'=> '25'),
        array('codigo_dane'=> '25181', 'nombre'=> 'CHOACHI', 'departamento'=> '25'),
        array('codigo_dane'=> '25183', 'nombre'=> 'CHOCONTA', 'departamento'=> '25'),
        array('codigo_dane'=> '25200', 'nombre'=> 'COGUA', 'departamento'=> '25'),
        array('codigo_dane'=> '25214', 'nombre'=> 'COTA', 'departamento'=> '25'),
        array('codigo_dane'=> '25224', 'nombre'=> 'CUCUNUBA', 'departamento'=> '25'),
        array('codigo_dane'=> '25245', 'nombre'=> 'EL COLEGIO', 'departamento'=> '25'),
        array('codigo_dane'=> '25258', 'nombre'=> 'EL PEÑON', 'departamento'=> '25'),
        array('codigo_dane'=> '25260', 'nombre'=> 'EL ROSAL', 'departamento'=> '25'),
        array('codigo_dane'=> '25269', 'nombre'=> 'FACATATIVA', 'departamento'=> '25'),
        array('codigo_dane'=> '25279', 'nombre'=> 'FOMEQUE', 'departamento'=> '25'),
        array('codigo_dane'=> '25281', 'nombre'=> 'FOSCA', 'departamento'=> '25'),
        array('codigo_dane'=> '25286', 'nombre'=> 'FUNZA', 'departamento'=> '25'),
        array('codigo_dane'=> '25288', 'nombre'=> 'FUQUENE', 'departamento'=> '25'),
        array('codigo_dane'=> '25290', 'nombre'=> 'FUSAGASUGA', 'departamento'=> '25'),
        array('codigo_dane'=> '25293', 'nombre'=> 'GACHALA', 'departamento'=> '25'),
        array('codigo_dane'=> '25295', 'nombre'=> 'GACHANCIPA', 'departamento'=> '25'),
        array('codigo_dane'=> '25297', 'nombre'=> 'GACHETA', 'departamento'=> '25'),
        array('codigo_dane'=> '25299', 'nombre'=> 'GAMA', 'departamento'=> '25'),
        array('codigo_dane'=> '25307', 'nombre'=> 'GIRARDOT', 'departamento'=> '25'),
        array('codigo_dane'=> '25312', 'nombre'=> 'GRANADA', 'departamento'=> '25'),
        array('codigo_dane'=> '25317', 'nombre'=> 'GUACHETA', 'departamento'=> '25'),
        array('codigo_dane'=> '25320', 'nombre'=> 'GUADUAS', 'departamento'=> '25'),
        array('codigo_dane'=> '25322', 'nombre'=> 'GUASCA', 'departamento'=> '25'),
        array('codigo_dane'=> '25324', 'nombre'=> 'GUATAQUI', 'departamento'=> '25'),
        array('codigo_dane'=> '25326', 'nombre'=> 'GUATAVITA', 'departamento'=> '25'),
        array('codigo_dane'=> '25328', 'nombre'=> 'GUAYABAL DE SIQUIMA', 'departamento'=> '25'),
        array('codigo_dane'=> '25335', 'nombre'=> 'GUAYABETAL', 'departamento'=> '25'),
        array('codigo_dane'=> '25339', 'nombre'=> 'GUTIERREZ', 'departamento'=> '25'),
        array('codigo_dane'=> '25368', 'nombre'=> 'JERUSALEN', 'departamento'=> '25'),
        array('codigo_dane'=> '25372', 'nombre'=> 'JUNIN', 'departamento'=> '25'),
        array('codigo_dane'=> '25377', 'nombre'=> 'LA CALERA', 'departamento'=> '25'),
        array('codigo_dane'=> '25386', 'nombre'=> 'LA MESA', 'departamento'=> '25'),
        array('codigo_dane'=> '25394', 'nombre'=> 'LA PALMA', 'departamento'=> '25'),
        array('codigo_dane'=> '25398', 'nombre'=> 'LA PEÑA', 'departamento'=> '25'),
        array('codigo_dane'=> '25402', 'nombre'=> 'LA VEGA', 'departamento'=> '25'),
        array('codigo_dane'=> '25407', 'nombre'=> 'LENGUAZAQUE', 'departamento'=> '25'),
        array('codigo_dane'=> '25426', 'nombre'=> 'MACHETA', 'departamento'=> '25'),
        array('codigo_dane'=> '25430', 'nombre'=> 'MADRID', 'departamento'=> '25'),
        array('codigo_dane'=> '25436', 'nombre'=> 'MANTA', 'departamento'=> '25'),
        array('codigo_dane'=> '25438', 'nombre'=> 'MEDINA', 'departamento'=> '25'),
        array('codigo_dane'=> '25473', 'nombre'=> 'MOSQUERA', 'departamento'=> '25'),
        array('codigo_dane'=> '25483', 'nombre'=> 'NARIÑO', 'departamento'=> '25'),
        array('codigo_dane'=> '25486', 'nombre'=> 'NEMOCON', 'departamento'=> '25'),
        array('codigo_dane'=> '25488', 'nombre'=> 'NILO', 'departamento'=> '25'),
        array('codigo_dane'=> '25489', 'nombre'=> 'NIMAIMA', 'departamento'=> '25'),
        array('codigo_dane'=> '25491', 'nombre'=> 'NOCAIMA', 'departamento'=> '25'),
        array('codigo_dane'=> '25506', 'nombre'=> 'VENECIA', 'departamento'=> '25'),
        array('codigo_dane'=> '25513', 'nombre'=> 'PACHO', 'departamento'=> '25'),
        array('codigo_dane'=> '25518', 'nombre'=> 'PAIME', 'departamento'=> '25'),
        array('codigo_dane'=> '25524', 'nombre'=> 'PANDI', 'departamento'=> '25'),
        array('codigo_dane'=> '25530', 'nombre'=> 'PARATEBUENO', 'departamento'=> '25'),
        array('codigo_dane'=> '25535', 'nombre'=> 'PASCA', 'departamento'=> '25'),
        array('codigo_dane'=> '25572', 'nombre'=> 'PUERTO SALGAR', 'departamento'=> '25'),
        array('codigo_dane'=> '25580', 'nombre'=> 'PULI', 'departamento'=> '25'),
        array('codigo_dane'=> '25592', 'nombre'=> 'QUEBRADANEGRA', 'departamento'=> '25'),
        array('codigo_dane'=> '25594', 'nombre'=> 'QUETAME', 'departamento'=> '25'),
        array('codigo_dane'=> '25596', 'nombre'=> 'QUIPILE', 'departamento'=> '25'),
        array('codigo_dane'=> '25599', 'nombre'=> 'APULO', 'departamento'=> '25'),
        array('codigo_dane'=> '25612', 'nombre'=> 'RICAURTE', 'departamento'=> '25'),
        array('codigo_dane'=> '25645', 'nombre'=> 'SAN ANTONIO DEL TEQUENDAMA', 'departamento'=> '25'),
        array('codigo_dane'=> '25649', 'nombre'=> 'SAN BERNARDO', 'departamento'=> '25'),
        array('codigo_dane'=> '25653', 'nombre'=> 'SAN CAYETANO', 'departamento'=> '25'),
        array('codigo_dane'=> '25658', 'nombre'=> 'SAN FRANCISCO', 'departamento'=> '25'),
        array('codigo_dane'=> '25662', 'nombre'=> 'SAN JUAN DE RIO SECO', 'departamento'=> '25'),
        array('codigo_dane'=> '25718', 'nombre'=> 'SASAIMA', 'departamento'=> '25'),
        array('codigo_dane'=> '25736', 'nombre'=> 'SESQUILE', 'departamento'=> '25'),
        array('codigo_dane'=> '25740', 'nombre'=> 'SIBATE', 'departamento'=> '25'),
        array('codigo_dane'=> '25743', 'nombre'=> 'SILVANIA', 'departamento'=> '25'),
        array('codigo_dane'=> '25745', 'nombre'=> 'SIMIJACA', 'departamento'=> '25'),
        array('codigo_dane'=> '25754', 'nombre'=> 'SOACHA', 'departamento'=> '25'),
        array('codigo_dane'=> '25758', 'nombre'=> 'SOPO', 'departamento'=> '25'),
        array('codigo_dane'=> '25769', 'nombre'=> 'SUBACHOQUE', 'departamento'=> '25'),
        array('codigo_dane'=> '25772', 'nombre'=> 'SUESCA', 'departamento'=> '25'),
        array('codigo_dane'=> '25777', 'nombre'=> 'SUPATA', 'departamento'=> '25'),
        array('codigo_dane'=> '25779', 'nombre'=> 'SUSA', 'departamento'=> '25'),
        array('codigo_dane'=> '25781', 'nombre'=> 'SUTATAUSA', 'departamento'=> '25'),
        array('codigo_dane'=> '25785', 'nombre'=> 'TABIO', 'departamento'=> '25'),
        array('codigo_dane'=> '25793', 'nombre'=> 'TAUSA', 'departamento'=> '25'),
        array('codigo_dane'=> '25797', 'nombre'=> 'TENA', 'departamento'=> '25'),
        array('codigo_dane'=> '25799', 'nombre'=> 'TENJO', 'departamento'=> '25'),
        array('codigo_dane'=> '25805', 'nombre'=> 'TIBACUY', 'departamento'=> '25'),
        array('codigo_dane'=> '25807', 'nombre'=> 'TIBIRITA', 'departamento'=> '25'),
        array('codigo_dane'=> '25815', 'nombre'=> 'TOCAIMA', 'departamento'=> '25'),
        array('codigo_dane'=> '25817', 'nombre'=> 'TOCANCIPA', 'departamento'=> '25'),
        array('codigo_dane'=> '25823', 'nombre'=> 'TOPAIPI', 'departamento'=> '25'),
        array('codigo_dane'=> '25839', 'nombre'=> 'UBALA', 'departamento'=> '25'),
        array('codigo_dane'=> '25841', 'nombre'=> 'UBAQUE', 'departamento'=> '25'),
        array('codigo_dane'=> '25843', 'nombre'=> 'VILLA DE SAN DIEGO DE UBATE', 'departamento'=> '25'),
        array('codigo_dane'=> '25845', 'nombre'=> 'UNE', 'departamento'=> '25'),
        array('codigo_dane'=> '25851', 'nombre'=> 'UTICA', 'departamento'=> '25'),
        array('codigo_dane'=> '25862', 'nombre'=> 'VERGARA', 'departamento'=> '25'),
        array('codigo_dane'=> '25867', 'nombre'=> 'VIANI', 'departamento'=> '25'),
        array('codigo_dane'=> '25871', 'nombre'=> 'VILLAGOMEZ', 'departamento'=> '25'),
        array('codigo_dane'=> '25873', 'nombre'=> 'VILLAPINZON', 'departamento'=> '25'),
        array('codigo_dane'=> '25875', 'nombre'=> 'VILLETA', 'departamento'=> '25'),
        array('codigo_dane'=> '25878', 'nombre'=> 'VIOTA', 'departamento'=> '25'),
        array('codigo_dane'=> '25885', 'nombre'=> 'YACOPI', 'departamento'=> '25'),
        array('codigo_dane'=> '25898', 'nombre'=> 'ZIPACON', 'departamento'=> '25'),
        array('codigo_dane'=> '25899', 'nombre'=> 'ZIPAQUIRA', 'departamento'=> '25'),
        array('codigo_dane'=> '27001', 'nombre'=> 'QUIBDO', 'departamento'=> '27'),
        array('codigo_dane'=> '27006', 'nombre'=> 'ACANDI', 'departamento'=> '27'),
        array('codigo_dane'=> '27025', 'nombre'=> 'ALTO BAUDO', 'departamento'=> '27'),
        array('codigo_dane'=> '27050', 'nombre'=> 'ATRATO', 'departamento'=> '27'),
        array('codigo_dane'=> '27073', 'nombre'=> 'BAGADO', 'departamento'=> '27'),
        array('codigo_dane'=> '27075', 'nombre'=> 'BAHIA SOLANO', 'departamento'=> '27'),
        array('codigo_dane'=> '27077', 'nombre'=> 'BAJO BAUDO', 'departamento'=> '27'),
        array('codigo_dane'=> '27099', 'nombre'=> 'BOJAYA', 'departamento'=> '27'),
        array('codigo_dane'=> '27135', 'nombre'=> 'EL CANTON DEL SAN PABLO', 'departamento'=> '27'),
        array('codigo_dane'=> '27150', 'nombre'=> 'CARMEN DEL DARIEN', 'departamento'=> '27'),
        array('codigo_dane'=> '27160', 'nombre'=> 'CERTEGUI', 'departamento'=> '27'),
        array('codigo_dane'=> '27205', 'nombre'=> 'CONDOTO', 'departamento'=> '27'),
        array('codigo_dane'=> '27245', 'nombre'=> 'EL CARMEN DE ATRATO', 'departamento'=> '27'),
        array('codigo_dane'=> '27250', 'nombre'=> 'EL LITORAL DEL SAN JUAN', 'departamento'=> '27'),
        array('codigo_dane'=> '27361', 'nombre'=> 'ISTMINA', 'departamento'=> '27'),
        array('codigo_dane'=> '27372', 'nombre'=> 'JURADO', 'departamento'=> '27'),
        array('codigo_dane'=> '27413', 'nombre'=> 'LLORO', 'departamento'=> '27'),
        array('codigo_dane'=> '27425', 'nombre'=> 'MEDIO ATRATO', 'departamento'=> '27'),
        array('codigo_dane'=> '27430', 'nombre'=> 'MEDIO BAUDO', 'departamento'=> '27'),
        array('codigo_dane'=> '27450', 'nombre'=> 'MEDIO SAN JUAN', 'departamento'=> '27'),
        array('codigo_dane'=> '27491', 'nombre'=> 'NOVITA', 'departamento'=> '27'),
        array('codigo_dane'=> '27495', 'nombre'=> 'NUQUI', 'departamento'=> '27'),
        array('codigo_dane'=> '27580', 'nombre'=> 'RIO IRO', 'departamento'=> '27'),
        array('codigo_dane'=> '27600', 'nombre'=> 'RIO QUITO', 'departamento'=> '27'),
        array('codigo_dane'=> '27615', 'nombre'=> 'RIOSUCIO', 'departamento'=> '27'),
        array('codigo_dane'=> '27660', 'nombre'=> 'SAN JOSE DEL PALMAR', 'departamento'=> '27'),
        array('codigo_dane'=> '27745', 'nombre'=> 'SIPI', 'departamento'=> '27'),
        array('codigo_dane'=> '27787', 'nombre'=> 'TADO', 'departamento'=> '27'),
        array('codigo_dane'=> '27800', 'nombre'=> 'UNGUIA', 'departamento'=> '27'),
        array('codigo_dane'=> '27810', 'nombre'=> 'UNION PANAMERICANA', 'departamento'=> '27'),
        array('codigo_dane'=> '41001', 'nombre'=> 'NEIVA', 'departamento'=> '41'),
        array('codigo_dane'=> '41006', 'nombre'=> 'ACEVEDO', 'departamento'=> '41'),
        array('codigo_dane'=> '41013', 'nombre'=> 'AGRADO', 'departamento'=> '41'),
        array('codigo_dane'=> '41016', 'nombre'=> 'AIPE', 'departamento'=> '41'),
        array('codigo_dane'=> '41020', 'nombre'=> 'ALGECIRAS', 'departamento'=> '41'),
        array('codigo_dane'=> '41026', 'nombre'=> 'ALTAMIRA', 'departamento'=> '41'),
        array('codigo_dane'=> '41078', 'nombre'=> 'BARAYA', 'departamento'=> '41'),
        array('codigo_dane'=> '41132', 'nombre'=> 'CAMPOALEGRE', 'departamento'=> '41'),
        array('codigo_dane'=> '41206', 'nombre'=> 'COLOMBIA', 'departamento'=> '41'),
        array('codigo_dane'=> '41244', 'nombre'=> 'ELIAS', 'departamento'=> '41'),
        array('codigo_dane'=> '41298', 'nombre'=> 'GARZON', 'departamento'=> '41'),
        array('codigo_dane'=> '41306', 'nombre'=> 'GIGANTE', 'departamento'=> '41'),
        array('codigo_dane'=> '41319', 'nombre'=> 'GUADALUPE', 'departamento'=> '41'),
        array('codigo_dane'=> '41349', 'nombre'=> 'HOBO', 'departamento'=> '41'),
        array('codigo_dane'=> '41357', 'nombre'=> 'IQUIRA', 'departamento'=> '41'),
        array('codigo_dane'=> '41359', 'nombre'=> 'ISNOS', 'departamento'=> '41'),
        array('codigo_dane'=> '41378', 'nombre'=> 'LA ARGENTINA', 'departamento'=> '41'),
        array('codigo_dane'=> '41396', 'nombre'=> 'LA PLATA', 'departamento'=> '41'),
        array('codigo_dane'=> '41483', 'nombre'=> 'NATAGA', 'departamento'=> '41'),
        array('codigo_dane'=> '41503', 'nombre'=> 'OPORAPA', 'departamento'=> '41'),
        array('codigo_dane'=> '41518', 'nombre'=> 'PAICOL', 'departamento'=> '41'),
        array('codigo_dane'=> '41524', 'nombre'=> 'PALERMO', 'departamento'=> '41'),
        array('codigo_dane'=> '41530', 'nombre'=> 'PALESTINA', 'departamento'=> '41'),
        array('codigo_dane'=> '41548', 'nombre'=> 'PITAL', 'departamento'=> '41'),
        array('codigo_dane'=> '41551', 'nombre'=> 'PITALITO', 'departamento'=> '41'),
        array('codigo_dane'=> '41615', 'nombre'=> 'RIVERA', 'departamento'=> '41'),
        array('codigo_dane'=> '41660', 'nombre'=> 'SALADOBLANCO', 'departamento'=> '41'),
        array('codigo_dane'=> '41668', 'nombre'=> 'SAN AGUSTIN', 'departamento'=> '41'),
        array('codigo_dane'=> '41676', 'nombre'=> 'SANTA MARIA', 'departamento'=> '41'),
        array('codigo_dane'=> '41770', 'nombre'=> 'SUAZA', 'departamento'=> '41'),
        array('codigo_dane'=> '41791', 'nombre'=> 'TARQUI', 'departamento'=> '41'),
        array('codigo_dane'=> '41797', 'nombre'=> 'TESALIA', 'departamento'=> '41'),
        array('codigo_dane'=> '41799', 'nombre'=> 'TELLO', 'departamento'=> '41'),
        array('codigo_dane'=> '41801', 'nombre'=> 'TERUEL', 'departamento'=> '41'),
        array('codigo_dane'=> '41807', 'nombre'=> 'TIMANA', 'departamento'=> '41'),
        array('codigo_dane'=> '41872', 'nombre'=> 'VILLAVIEJA', 'departamento'=> '41'),
        array('codigo_dane'=> '41885', 'nombre'=> 'YAGUARA', 'departamento'=> '41'),
        array('codigo_dane'=> '44001', 'nombre'=> 'RIOHACHA', 'departamento'=> '44'),
        array('codigo_dane'=> '44035', 'nombre'=> 'ALBANIA', 'departamento'=> '44'),
        array('codigo_dane'=> '44078', 'nombre'=> 'BARRANCAS', 'departamento'=> '44'),
        array('codigo_dane'=> '44090', 'nombre'=> 'DIBULLA', 'departamento'=> '44'),
        array('codigo_dane'=> '44098', 'nombre'=> 'DISTRACCION', 'departamento'=> '44'),
        array('codigo_dane'=> '44110', 'nombre'=> 'EL MOLINO', 'departamento'=> '44'),
        array('codigo_dane'=> '44279', 'nombre'=> 'FONSECA', 'departamento'=> '44'),
        array('codigo_dane'=> '44378', 'nombre'=> 'HATONUEVO', 'departamento'=> '44'),
        array('codigo_dane'=> '44420', 'nombre'=> 'LA JAGUA DEL PILAR', 'departamento'=> '44'),
        array('codigo_dane'=> '44430', 'nombre'=> 'MAICAO', 'departamento'=> '44'),
        array('codigo_dane'=> '44560', 'nombre'=> 'MANAURE', 'departamento'=> '44'),
        array('codigo_dane'=> '44650', 'nombre'=> 'SAN JUAN DEL CESAR', 'departamento'=> '44'),
        array('codigo_dane'=> '44847', 'nombre'=> 'URIBIA', 'departamento'=> '44'),
        array('codigo_dane'=> '44855', 'nombre'=> 'URUMITA', 'departamento'=> '44'),
        array('codigo_dane'=> '44874', 'nombre'=> 'VILLANUEVA', 'departamento'=> '44'),
        array('codigo_dane'=> '47001', 'nombre'=> 'SANTA MARTA', 'departamento'=> '47'),
        array('codigo_dane'=> '47030', 'nombre'=> 'ALGARROBO', 'departamento'=> '47'),
        array('codigo_dane'=> '47053', 'nombre'=> 'ARACATACA', 'departamento'=> '47'),
        array('codigo_dane'=> '47058', 'nombre'=> 'ARIGUANI', 'departamento'=> '47'),
        array('codigo_dane'=> '47161', 'nombre'=> 'CERRO SAN ANTONIO', 'departamento'=> '47'),
        array('codigo_dane'=> '47170', 'nombre'=> 'CHIBOLO', 'departamento'=> '47'),
        array('codigo_dane'=> '47189', 'nombre'=> 'CIENAGA', 'departamento'=> '47'),
        array('codigo_dane'=> '47205', 'nombre'=> 'CONCORDIA', 'departamento'=> '47'),
        array('codigo_dane'=> '47245', 'nombre'=> 'EL BANCO', 'departamento'=> '47'),
        array('codigo_dane'=> '47258', 'nombre'=> 'EL PIÑON', 'departamento'=> '47'),
        array('codigo_dane'=> '47268', 'nombre'=> 'EL RETEN', 'departamento'=> '47'),
        array('codigo_dane'=> '47288', 'nombre'=> 'FUNDACION', 'departamento'=> '47'),
        array('codigo_dane'=> '47318', 'nombre'=> 'GUAMAL', 'departamento'=> '47'),
        array('codigo_dane'=> '47460', 'nombre'=> 'NUEVA GRANADA', 'departamento'=> '47'),
        array('codigo_dane'=> '47541', 'nombre'=> 'PEDRAZA', 'departamento'=> '47'),
        array('codigo_dane'=> '47545', 'nombre'=> 'PIJIÑO DEL CARMEN', 'departamento'=> '47'),
        array('codigo_dane'=> '47551', 'nombre'=> 'PIVIJAY', 'departamento'=> '47'),
        array('codigo_dane'=> '47555', 'nombre'=> 'PLATO', 'departamento'=> '47'),
        array('codigo_dane'=> '47570', 'nombre'=> 'PUEBLOVIEJO', 'departamento'=> '47'),
        array('codigo_dane'=> '47605', 'nombre'=> 'REMOLINO', 'departamento'=> '47'),
        array('codigo_dane'=> '47660', 'nombre'=> 'SABANAS DE SAN ANGEL', 'departamento'=> '47'),
        array('codigo_dane'=> '47675', 'nombre'=> 'SALAMINA', 'departamento'=> '47'),
        array('codigo_dane'=> '47692', 'nombre'=> 'SAN SEBASTIAN DE BUENAVISTA', 'departamento'=> '47'),
        array('codigo_dane'=> '47703', 'nombre'=> 'SAN ZENON', 'departamento'=> '47'),
        array('codigo_dane'=> '47707', 'nombre'=> 'SANTA ANA', 'departamento'=> '47'),
        array('codigo_dane'=> '47720', 'nombre'=> 'SANTA BARBARA DE PINTO', 'departamento'=> '47'),
        array('codigo_dane'=> '47745', 'nombre'=> 'SITIONUEVO', 'departamento'=> '47'),
        array('codigo_dane'=> '47798', 'nombre'=> 'TENERIFE', 'departamento'=> '47'),
        array('codigo_dane'=> '47960', 'nombre'=> 'ZAPAYAN', 'departamento'=> '47'),
        array('codigo_dane'=> '47980', 'nombre'=> 'ZONA BANANERA', 'departamento'=> '47'),
        array('codigo_dane'=> '50001', 'nombre'=> 'VILLAVICENCIO', 'departamento'=> '50'),
        array('codigo_dane'=> '50006', 'nombre'=> 'ACACIAS', 'departamento'=> '50'),
        array('codigo_dane'=> '50110', 'nombre'=> 'BARRANCA DE UPIA', 'departamento'=> '50'),
        array('codigo_dane'=> '50124', 'nombre'=> 'CABUYARO', 'departamento'=> '50'),
        array('codigo_dane'=> '50150', 'nombre'=> 'CASTILLA LA NUEVA', 'departamento'=> '50'),
        array('codigo_dane'=> '50223', 'nombre'=> 'CUBARRAL', 'departamento'=> '50'),
        array('codigo_dane'=> '50226', 'nombre'=> 'CUMARAL', 'departamento'=> '50'),
        array('codigo_dane'=> '50245', 'nombre'=> 'EL CALVARIO', 'departamento'=> '50'),
        array('codigo_dane'=> '50251', 'nombre'=> 'EL CASTILLO', 'departamento'=> '50'),
        array('codigo_dane'=> '50270', 'nombre'=> 'EL DORADO', 'departamento'=> '50'),
        array('codigo_dane'=> '50287', 'nombre'=> 'FUENTE DE ORO', 'departamento'=> '50'),
        array('codigo_dane'=> '50313', 'nombre'=> 'GRANADA', 'departamento'=> '50'),
        array('codigo_dane'=> '50318', 'nombre'=> 'GUAMAL', 'departamento'=> '50'),
        array('codigo_dane'=> '50325', 'nombre'=> 'MAPIRIPAN', 'departamento'=> '50'),
        array('codigo_dane'=> '50330', 'nombre'=> 'MESETAS', 'departamento'=> '50'),
        array('codigo_dane'=> '50350', 'nombre'=> 'LA MACARENA', 'departamento'=> '50'),
        array('codigo_dane'=> '50370', 'nombre'=> 'URIBE', 'departamento'=> '50'),
        array('codigo_dane'=> '50400', 'nombre'=> 'LEJANIAS', 'departamento'=> '50'),
        array('codigo_dane'=> '50450', 'nombre'=> 'PUERTO CONCORDIA', 'departamento'=> '50'),
        array('codigo_dane'=> '50568', 'nombre'=> 'PUERTO GAITAN', 'departamento'=> '50'),
        array('codigo_dane'=> '50573', 'nombre'=> 'PUERTO LOPEZ', 'departamento'=> '50'),
        array('codigo_dane'=> '50577', 'nombre'=> 'PUERTO LLERAS', 'departamento'=> '50'),
        array('codigo_dane'=> '50590', 'nombre'=> 'PUERTO RICO', 'departamento'=> '50'),
        array('codigo_dane'=> '50606', 'nombre'=> 'RESTREPO', 'departamento'=> '50'),
        array('codigo_dane'=> '50680', 'nombre'=> 'SAN CARLOS DE GUAROA', 'departamento'=> '50'),
        array('codigo_dane'=> '50683', 'nombre'=> 'SAN JUAN DE ARAMA', 'departamento'=> '50'),
        array('codigo_dane'=> '50686', 'nombre'=> 'SAN JUANITO', 'departamento'=> '50'),
        array('codigo_dane'=> '50689', 'nombre'=> 'SAN MARTIN', 'departamento'=> '50'),
        array('codigo_dane'=> '50711', 'nombre'=> 'VISTAHERMOSA', 'departamento'=> '50'),
        array('codigo_dane'=> '52001', 'nombre'=> 'PASTO', 'departamento'=> '52'),
        array('codigo_dane'=> '52019', 'nombre'=> 'ALBAN', 'departamento'=> '52'),
        array('codigo_dane'=> '52022', 'nombre'=> 'ALDANA', 'departamento'=> '52'),
        array('codigo_dane'=> '52036', 'nombre'=> 'ANCUYA', 'departamento'=> '52'),
        array('codigo_dane'=> '52051', 'nombre'=> 'ARBOLEDA', 'departamento'=> '52'),
        array('codigo_dane'=> '52079', 'nombre'=> 'BARBACOAS', 'departamento'=> '52'),
        array('codigo_dane'=> '52083', 'nombre'=> 'BELEN', 'departamento'=> '52'),
        array('codigo_dane'=> '52110', 'nombre'=> 'BUESACO', 'departamento'=> '52'),
        array('codigo_dane'=> '52203', 'nombre'=> 'COLON', 'departamento'=> '52'),
        array('codigo_dane'=> '52207', 'nombre'=> 'CONSACA', 'departamento'=> '52'),
        array('codigo_dane'=> '52210', 'nombre'=> 'CONTADERO', 'departamento'=> '52'),
        array('codigo_dane'=> '52215', 'nombre'=> 'CORDOBA', 'departamento'=> '52'),
        array('codigo_dane'=> '52224', 'nombre'=> 'CUASPUD', 'departamento'=> '52'),
        array('codigo_dane'=> '52227', 'nombre'=> 'CUMBAL', 'departamento'=> '52'),
        array('codigo_dane'=> '52233', 'nombre'=> 'CUMBITARA', 'departamento'=> '52'),
        array('codigo_dane'=> '52240', 'nombre'=> 'CHACHAGsI', 'departamento'=> '52'),
        array('codigo_dane'=> '52250', 'nombre'=> 'EL CHARCO', 'departamento'=> '52'),
        array('codigo_dane'=> '52254', 'nombre'=> 'EL PEÑOL', 'departamento'=> '52'),
        array('codigo_dane'=> '52256', 'nombre'=> 'EL ROSARIO', 'departamento'=> '52'),
        array('codigo_dane'=> '52258', 'nombre'=> 'EL TABLON DE GOMEZ', 'departamento'=> '52'),
        array('codigo_dane'=> '52260', 'nombre'=> 'EL TAMBO', 'departamento'=> '52'),
        array('codigo_dane'=> '52287', 'nombre'=> 'FUNES', 'departamento'=> '52'),
        array('codigo_dane'=> '52317', 'nombre'=> 'GUACHUCAL', 'departamento'=> '52'),
        array('codigo_dane'=> '52320', 'nombre'=> 'GUAITARILLA', 'departamento'=> '52'),
        array('codigo_dane'=> '52323', 'nombre'=> 'GUALMATAN', 'departamento'=> '52'),
        array('codigo_dane'=> '52352', 'nombre'=> 'ILES', 'departamento'=> '52'),
        array('codigo_dane'=> '52354', 'nombre'=> 'IMUES', 'departamento'=> '52'),
        array('codigo_dane'=> '52356', 'nombre'=> 'IPIALES', 'departamento'=> '52'),
        array('codigo_dane'=> '52378', 'nombre'=> 'LA CRUZ', 'departamento'=> '52'),
        array('codigo_dane'=> '52381', 'nombre'=> 'LA FLORIDA', 'departamento'=> '52'),
        array('codigo_dane'=> '52385', 'nombre'=> 'LA LLANADA', 'departamento'=> '52'),
        array('codigo_dane'=> '52390', 'nombre'=> 'LA TOLA', 'departamento'=> '52'),
        array('codigo_dane'=> '52399', 'nombre'=> 'LA UNION', 'departamento'=> '52'),
        array('codigo_dane'=> '52405', 'nombre'=> 'LEIVA', 'departamento'=> '52'),
        array('codigo_dane'=> '52411', 'nombre'=> 'LINARES', 'departamento'=> '52'),
        array('codigo_dane'=> '52418', 'nombre'=> 'LOS ANDES', 'departamento'=> '52'),
        array('codigo_dane'=> '52427', 'nombre'=> 'MAGsI', 'departamento'=> '52'),
        array('codigo_dane'=> '52435', 'nombre'=> 'MALLAMA', 'departamento'=> '52'),
        array('codigo_dane'=> '52473', 'nombre'=> 'MOSQUERA', 'departamento'=> '52'),
        array('codigo_dane'=> '52480', 'nombre'=> 'NARIÑO', 'departamento'=> '52'),
        array('codigo_dane'=> '52490', 'nombre'=> 'OLAYA HERRERA', 'departamento'=> '52'),
        array('codigo_dane'=> '52506', 'nombre'=> 'OSPINA', 'departamento'=> '52'),
        array('codigo_dane'=> '52520', 'nombre'=> 'FRANCISCO PIZARRO', 'departamento'=> '52'),
        array('codigo_dane'=> '52540', 'nombre'=> 'POLICARPA', 'departamento'=> '52'),
        array('codigo_dane'=> '52560', 'nombre'=> 'POTOSI', 'departamento'=> '52'),
        array('codigo_dane'=> '52565', 'nombre'=> 'PROVIDENCIA', 'departamento'=> '52'),
        array('codigo_dane'=> '52573', 'nombre'=> 'PUERRES', 'departamento'=> '52'),
        array('codigo_dane'=> '52585', 'nombre'=> 'PUPIALES', 'departamento'=> '52'),
        array('codigo_dane'=> '52612', 'nombre'=> 'RICAURTE', 'departamento'=> '52'),
        array('codigo_dane'=> '52621', 'nombre'=> 'ROBERTO PAYAN', 'departamento'=> '52'),
        array('codigo_dane'=> '52678', 'nombre'=> 'SAMANIEGO', 'departamento'=> '52'),
        array('codigo_dane'=> '52683', 'nombre'=> 'SANDONA', 'departamento'=> '52'),
        array('codigo_dane'=> '52685', 'nombre'=> 'SAN BERNARDO', 'departamento'=> '52'),
        array('codigo_dane'=> '52687', 'nombre'=> 'SAN LORENZO', 'departamento'=> '52'),
        array('codigo_dane'=> '52693', 'nombre'=> 'SAN PABLO', 'departamento'=> '52'),
        array('codigo_dane'=> '52694', 'nombre'=> 'SAN PEDRO DE CARTAGO', 'departamento'=> '52'),
        array('codigo_dane'=> '52696', 'nombre'=> 'SANTA BARBARA', 'departamento'=> '52'),
        array('codigo_dane'=> '52699', 'nombre'=> 'SANTACRUZ', 'departamento'=> '52'),
        array('codigo_dane'=> '52720', 'nombre'=> 'SAPUYES', 'departamento'=> '52'),
        array('codigo_dane'=> '52786', 'nombre'=> 'TAMINANGO', 'departamento'=> '52'),
        array('codigo_dane'=> '52788', 'nombre'=> 'TANGUA', 'departamento'=> '52'),
        array('codigo_dane'=> '52835', 'nombre'=> 'SAN ANDRES DE TUMACO', 'departamento'=> '52'),
        array('codigo_dane'=> '52838', 'nombre'=> 'TUQUERRES', 'departamento'=> '52'),
        array('codigo_dane'=> '52885', 'nombre'=> 'YACUANQUER', 'departamento'=> '52'),
        array('codigo_dane'=> '54001', 'nombre'=> 'CUCUTA', 'departamento'=> '54'),
        array('codigo_dane'=> '54003', 'nombre'=> 'ABREGO', 'departamento'=> '54'),
        array('codigo_dane'=> '54051', 'nombre'=> 'ARBOLEDAS', 'departamento'=> '54'),
        array('codigo_dane'=> '54099', 'nombre'=> 'BOCHALEMA', 'departamento'=> '54'),
        array('codigo_dane'=> '54109', 'nombre'=> 'BUCARASICA', 'departamento'=> '54'),
        array('codigo_dane'=> '54125', 'nombre'=> 'CACOTA', 'departamento'=> '54'),
        array('codigo_dane'=> '54128', 'nombre'=> 'CACHIRA', 'departamento'=> '54'),
        array('codigo_dane'=> '54172', 'nombre'=> 'CHINACOTA', 'departamento'=> '54'),
        array('codigo_dane'=> '54174', 'nombre'=> 'CHITAGA', 'departamento'=> '54'),
        array('codigo_dane'=> '54206', 'nombre'=> 'CONVENCION', 'departamento'=> '54'),
        array('codigo_dane'=> '54223', 'nombre'=> 'CUCUTILLA', 'departamento'=> '54'),
        array('codigo_dane'=> '54239', 'nombre'=> 'DURANIA', 'departamento'=> '54'),
        array('codigo_dane'=> '54245', 'nombre'=> 'EL CARMEN', 'departamento'=> '54'),
        array('codigo_dane'=> '54250', 'nombre'=> 'EL TARRA', 'departamento'=> '54'),
        array('codigo_dane'=> '54261', 'nombre'=> 'EL ZULIA', 'departamento'=> '54'),
        array('codigo_dane'=> '54313', 'nombre'=> 'GRAMALOTE', 'departamento'=> '54'),
        array('codigo_dane'=> '54344', 'nombre'=> 'HACARI', 'departamento'=> '54'),
        array('codigo_dane'=> '54347', 'nombre'=> 'HERRAN', 'departamento'=> '54'),
        array('codigo_dane'=> '54377', 'nombre'=> 'LABATECA', 'departamento'=> '54'),
        array('codigo_dane'=> '54385', 'nombre'=> 'LA ESPERANZA', 'departamento'=> '54'),
        array('codigo_dane'=> '54398', 'nombre'=> 'LA PLAYA', 'departamento'=> '54'),
        array('codigo_dane'=> '54405', 'nombre'=> 'LOS PATIOS', 'departamento'=> '54'),
        array('codigo_dane'=> '54418', 'nombre'=> 'LOURDES', 'departamento'=> '54'),
        array('codigo_dane'=> '54480', 'nombre'=> 'MUTISCUA', 'departamento'=> '54'),
        array('codigo_dane'=> '54498', 'nombre'=> 'OCAÑA', 'departamento'=> '54'),
        array('codigo_dane'=> '54518', 'nombre'=> 'PAMPLONA', 'departamento'=> '54'),
        array('codigo_dane'=> '54520', 'nombre'=> 'PAMPLONITA', 'departamento'=> '54'),
        array('codigo_dane'=> '54553', 'nombre'=> 'PUERTO SANTANDER', 'departamento'=> '54'),
        array('codigo_dane'=> '54599', 'nombre'=> 'RAGONVALIA', 'departamento'=> '54'),
        array('codigo_dane'=> '54660', 'nombre'=> 'SALAZAR', 'departamento'=> '54'),
        array('codigo_dane'=> '54670', 'nombre'=> 'SAN CALIXTO', 'departamento'=> '54'),
        array('codigo_dane'=> '54673', 'nombre'=> 'SAN CAYETANO', 'departamento'=> '54'),
        array('codigo_dane'=> '54680', 'nombre'=> 'SANTIAGO', 'departamento'=> '54'),
        array('codigo_dane'=> '54720', 'nombre'=> 'SARDINATA', 'departamento'=> '54'),
        array('codigo_dane'=> '54743', 'nombre'=> 'SILOS', 'departamento'=> '54'),
        array('codigo_dane'=> '54800', 'nombre'=> 'TEORAMA', 'departamento'=> '54'),
        array('codigo_dane'=> '54810', 'nombre'=> 'TIBU', 'departamento'=> '54'),
        array('codigo_dane'=> '54820', 'nombre'=> 'TOLEDO', 'departamento'=> '54'),
        array('codigo_dane'=> '54871', 'nombre'=> 'VILLA CARO', 'departamento'=> '54'),
        array('codigo_dane'=> '54874', 'nombre'=> 'VILLA DEL ROSARIO', 'departamento'=> '54'),
        array('codigo_dane'=> '63001', 'nombre'=> 'ARMENIA', 'departamento'=> '63'),
        array('codigo_dane'=> '63111', 'nombre'=> 'BUENAVISTA', 'departamento'=> '63'),
        array('codigo_dane'=> '63130', 'nombre'=> 'CALARCA', 'departamento'=> '63'),
        array('codigo_dane'=> '63190', 'nombre'=> 'CIRCASIA', 'departamento'=> '63'),
        array('codigo_dane'=> '63212', 'nombre'=> 'CORDOBA', 'departamento'=> '63'),
        array('codigo_dane'=> '63272', 'nombre'=> 'FILANDIA', 'departamento'=> '63'),
        array('codigo_dane'=> '63302', 'nombre'=> 'GENOVA', 'departamento'=> '63'),
        array('codigo_dane'=> '63401', 'nombre'=> 'LA TEBAIDA', 'departamento'=> '63'),
        array('codigo_dane'=> '63470', 'nombre'=> 'MONTENEGRO', 'departamento'=> '63'),
        array('codigo_dane'=> '63548', 'nombre'=> 'PIJAO', 'departamento'=> '63'),
        array('codigo_dane'=> '63594', 'nombre'=> 'QUIMBAYA', 'departamento'=> '63'),
        array('codigo_dane'=> '63690', 'nombre'=> 'SALENTO', 'departamento'=> '63'),
        array('codigo_dane'=> '66001', 'nombre'=> 'PEREIRA', 'departamento'=> '66'),
        array('codigo_dane'=> '66045', 'nombre'=> 'APIA', 'departamento'=> '66'),
        array('codigo_dane'=> '66075', 'nombre'=> 'BALBOA', 'departamento'=> '66'),
        array('codigo_dane'=> '66088', 'nombre'=> 'BELEN DE UMBRIA', 'departamento'=> '66'),
        array('codigo_dane'=> '66170', 'nombre'=> 'DOSQUEBRADAS', 'departamento'=> '66'),
        array('codigo_dane'=> '66318', 'nombre'=> 'GUATICA', 'departamento'=> '66'),
        array('codigo_dane'=> '66383', 'nombre'=> 'LA CELIA', 'departamento'=> '66'),
        array('codigo_dane'=> '66400', 'nombre'=> 'LA VIRGINIA', 'departamento'=> '66'),
        array('codigo_dane'=> '66440', 'nombre'=> 'MARSELLA', 'departamento'=> '66'),
        array('codigo_dane'=> '66456', 'nombre'=> 'MISTRATO', 'departamento'=> '66'),
        array('codigo_dane'=> '66572', 'nombre'=> 'PUEBLO RICO', 'departamento'=> '66'),
        array('codigo_dane'=> '66594', 'nombre'=> 'QUINCHIA', 'departamento'=> '66'),
        array('codigo_dane'=> '66682', 'nombre'=> 'SANTA ROSA DE CABAL', 'departamento'=> '66'),
        array('codigo_dane'=> '66687', 'nombre'=> 'SANTUARIO', 'departamento'=> '66'),
        array('codigo_dane'=> '68001', 'nombre'=> 'BUCARAMANGA', 'departamento'=> '68'),
        array('codigo_dane'=> '68013', 'nombre'=> 'AGUADA', 'departamento'=> '68'),
        array('codigo_dane'=> '68020', 'nombre'=> 'ALBANIA', 'departamento'=> '68'),
        array('codigo_dane'=> '68051', 'nombre'=> 'ARATOCA', 'departamento'=> '68'),
        array('codigo_dane'=> '68077', 'nombre'=> 'BARBOSA', 'departamento'=> '68'),
        array('codigo_dane'=> '68079', 'nombre'=> 'BARICHARA', 'departamento'=> '68'),
        array('codigo_dane'=> '68081', 'nombre'=> 'BARRANCABERMEJA', 'departamento'=> '68'),
        array('codigo_dane'=> '68092', 'nombre'=> 'BETULIA', 'departamento'=> '68'),
        array('codigo_dane'=> '68101', 'nombre'=> 'BOLIVAR', 'departamento'=> '68'),
        array('codigo_dane'=> '68121', 'nombre'=> 'CABRERA', 'departamento'=> '68'),
        array('codigo_dane'=> '68132', 'nombre'=> 'CALIFORNIA', 'departamento'=> '68'),
        array('codigo_dane'=> '68147', 'nombre'=> 'CAPITANEJO', 'departamento'=> '68'),
        array('codigo_dane'=> '68152', 'nombre'=> 'CARCASI', 'departamento'=> '68'),
        array('codigo_dane'=> '68160', 'nombre'=> 'CEPITA', 'departamento'=> '68'),
        array('codigo_dane'=> '68162', 'nombre'=> 'CERRITO', 'departamento'=> '68'),
        array('codigo_dane'=> '68167', 'nombre'=> 'CHARALA', 'departamento'=> '68'),
        array('codigo_dane'=> '68169', 'nombre'=> 'CHARTA', 'departamento'=> '68'),
        array('codigo_dane'=> '68176', 'nombre'=> 'CHIMA', 'departamento'=> '68'),
        array('codigo_dane'=> '68179', 'nombre'=> 'CHIPATA', 'departamento'=> '68'),
        array('codigo_dane'=> '68190', 'nombre'=> 'CIMITARRA', 'departamento'=> '68'),
        array('codigo_dane'=> '68207', 'nombre'=> 'CONCEPCION', 'departamento'=> '68'),
        array('codigo_dane'=> '68209', 'nombre'=> 'CONFINES', 'departamento'=> '68'),
        array('codigo_dane'=> '68211', 'nombre'=> 'CONTRATACION', 'departamento'=> '68'),
        array('codigo_dane'=> '68217', 'nombre'=> 'COROMORO', 'departamento'=> '68'),
        array('codigo_dane'=> '68229', 'nombre'=> 'CURITI', 'departamento'=> '68'),
        array('codigo_dane'=> '68235', 'nombre'=> 'EL CARMEN DE CHUCURI', 'departamento'=> '68'),
        array('codigo_dane'=> '68245', 'nombre'=> 'EL GUACAMAYO', 'departamento'=> '68'),
        array('codigo_dane'=> '68250', 'nombre'=> 'EL PEÑON', 'departamento'=> '68'),
        array('codigo_dane'=> '68255', 'nombre'=> 'EL PLAYON', 'departamento'=> '68'),
        array('codigo_dane'=> '68264', 'nombre'=> 'ENCINO', 'departamento'=> '68'),
        array('codigo_dane'=> '68266', 'nombre'=> 'ENCISO', 'departamento'=> '68'),
        array('codigo_dane'=> '68271', 'nombre'=> 'FLORIAN', 'departamento'=> '68'),
        array('codigo_dane'=> '68276', 'nombre'=> 'FLORIDABLANCA', 'departamento'=> '68'),
        array('codigo_dane'=> '68296', 'nombre'=> 'GALAN', 'departamento'=> '68'),
        array('codigo_dane'=> '68298', 'nombre'=> 'GAMBITA', 'departamento'=> '68'),
        array('codigo_dane'=> '68307', 'nombre'=> 'GIRON', 'departamento'=> '68'),
        array('codigo_dane'=> '68318', 'nombre'=> 'GUACA', 'departamento'=> '68'),
        array('codigo_dane'=> '68320', 'nombre'=> 'GUADALUPE', 'departamento'=> '68'),
        array('codigo_dane'=> '68322', 'nombre'=> 'GUAPOTA', 'departamento'=> '68'),
        array('codigo_dane'=> '68324', 'nombre'=> 'GUAVATA', 'departamento'=> '68'),
        array('codigo_dane'=> '68327', 'nombre'=> 'GsEPSA', 'departamento'=> '68'),
        array('codigo_dane'=> '68344', 'nombre'=> 'HATO', 'departamento'=> '68'),
        array('codigo_dane'=> '68368', 'nombre'=> 'JESUS MARIA', 'departamento'=> '68'),
        array('codigo_dane'=> '68370', 'nombre'=> 'JORDAN', 'departamento'=> '68'),
        array('codigo_dane'=> '68377', 'nombre'=> 'LA BELLEZA', 'departamento'=> '68'),
        array('codigo_dane'=> '68385', 'nombre'=> 'LANDAZURI', 'departamento'=> '68'),
        array('codigo_dane'=> '68397', 'nombre'=> 'LA PAZ', 'departamento'=> '68'),
        array('codigo_dane'=> '68406', 'nombre'=> 'LEBRIJA', 'departamento'=> '68'),
        array('codigo_dane'=> '68418', 'nombre'=> 'LOS SANTOS', 'departamento'=> '68'),
        array('codigo_dane'=> '68425', 'nombre'=> 'MACARAVITA', 'departamento'=> '68'),
        array('codigo_dane'=> '68432', 'nombre'=> 'MALAGA', 'departamento'=> '68'),
        array('codigo_dane'=> '68444', 'nombre'=> 'MATANZA', 'departamento'=> '68'),
        array('codigo_dane'=> '68464', 'nombre'=> 'MOGOTES', 'departamento'=> '68'),
        array('codigo_dane'=> '68468', 'nombre'=> 'MOLAGAVITA', 'departamento'=> '68'),
        array('codigo_dane'=> '68498', 'nombre'=> 'OCAMONTE', 'departamento'=> '68'),
        array('codigo_dane'=> '68500', 'nombre'=> 'OIBA', 'departamento'=> '68'),
        array('codigo_dane'=> '68502', 'nombre'=> 'ONZAGA', 'departamento'=> '68'),
        array('codigo_dane'=> '68522', 'nombre'=> 'PALMAR', 'departamento'=> '68'),
        array('codigo_dane'=> '68524', 'nombre'=> 'PALMAS DEL SOCORRO', 'departamento'=> '68'),
        array('codigo_dane'=> '68533', 'nombre'=> 'PARAMO', 'departamento'=> '68'),
        array('codigo_dane'=> '68547', 'nombre'=> 'PIEDECUESTA', 'departamento'=> '68'),
        array('codigo_dane'=> '68549', 'nombre'=> 'PINCHOTE', 'departamento'=> '68'),
        array('codigo_dane'=> '68572', 'nombre'=> 'PUENTE NACIONAL', 'departamento'=> '68'),
        array('codigo_dane'=> '68573', 'nombre'=> 'PUERTO PARRA', 'departamento'=> '68'),
        array('codigo_dane'=> '68575', 'nombre'=> 'PUERTO WILCHES', 'departamento'=> '68'),
        array('codigo_dane'=> '68615', 'nombre'=> 'RIONEGRO', 'departamento'=> '68'),
        array('codigo_dane'=> '68655', 'nombre'=> 'SABANA DE TORRES', 'departamento'=> '68'),
        array('codigo_dane'=> '68669', 'nombre'=> 'SAN ANDRES', 'departamento'=> '68'),
        array('codigo_dane'=> '68673', 'nombre'=> 'SAN BENITO', 'departamento'=> '68'),
        array('codigo_dane'=> '68679', 'nombre'=> 'SAN GIL', 'departamento'=> '68'),
        array('codigo_dane'=> '68682', 'nombre'=> 'SAN JOAQUIN', 'departamento'=> '68'),
        array('codigo_dane'=> '68684', 'nombre'=> 'SAN JOSE DE MIRANDA', 'departamento'=> '68'),
        array('codigo_dane'=> '68686', 'nombre'=> 'SAN MIGUEL', 'departamento'=> '68'),
        array('codigo_dane'=> '68689', 'nombre'=> 'SAN VICENTE DE CHUCURI', 'departamento'=> '68'),
        array('codigo_dane'=> '68705', 'nombre'=> 'SANTA BARBARA', 'departamento'=> '68'),
        array('codigo_dane'=> '68720', 'nombre'=> 'SANTA HELENA DEL OPON', 'departamento'=> '68'),
        array('codigo_dane'=> '68745', 'nombre'=> 'SIMACOTA', 'departamento'=> '68'),
        array('codigo_dane'=> '68755', 'nombre'=> 'SOCORRO', 'departamento'=> '68'),
        array('codigo_dane'=> '68770', 'nombre'=> 'SUAITA', 'departamento'=> '68'),
        array('codigo_dane'=> '68773', 'nombre'=> 'SUCRE', 'departamento'=> '68'),
        array('codigo_dane'=> '68780', 'nombre'=> 'SURATA', 'departamento'=> '68'),
        array('codigo_dane'=> '68820', 'nombre'=> 'TONA', 'departamento'=> '68'),
        array('codigo_dane'=> '68855', 'nombre'=> 'VALLE DE SAN JOSE', 'departamento'=> '68'),
        array('codigo_dane'=> '68861', 'nombre'=> 'VELEZ', 'departamento'=> '68'),
        array('codigo_dane'=> '68867', 'nombre'=> 'VETAS', 'departamento'=> '68'),
        array('codigo_dane'=> '68872', 'nombre'=> 'VILLANUEVA', 'departamento'=> '68'),
        array('codigo_dane'=> '68895', 'nombre'=> 'ZAPATOCA', 'departamento'=> '68'),
        array('codigo_dane'=> '70001', 'nombre'=> 'SINCELEJO', 'departamento'=> '70'),
        array('codigo_dane'=> '70110', 'nombre'=> 'BUENAVISTA', 'departamento'=> '70'),
        array('codigo_dane'=> '70124', 'nombre'=> 'CAIMITO', 'departamento'=> '70'),
        array('codigo_dane'=> '70204', 'nombre'=> 'COLOSO', 'departamento'=> '70'),
        array('codigo_dane'=> '70215', 'nombre'=> 'COROZAL', 'departamento'=> '70'),
        array('codigo_dane'=> '70221', 'nombre'=> 'COVEÑAS', 'departamento'=> '70'),
        array('codigo_dane'=> '70230', 'nombre'=> 'CHALAN', 'departamento'=> '70'),
        array('codigo_dane'=> '70233', 'nombre'=> 'EL ROBLE', 'departamento'=> '70'),
        array('codigo_dane'=> '70235', 'nombre'=> 'GALERAS', 'departamento'=> '70'),
        array('codigo_dane'=> '70265', 'nombre'=> 'GUARANDA', 'departamento'=> '70'),
        array('codigo_dane'=> '70400', 'nombre'=> 'LA UNION', 'departamento'=> '70'),
        array('codigo_dane'=> '70418', 'nombre'=> 'LOS PALMITOS', 'departamento'=> '70'),
        array('codigo_dane'=> '70429', 'nombre'=> 'MAJAGUAL', 'departamento'=> '70'),
        array('codigo_dane'=> '70473', 'nombre'=> 'MORROA', 'departamento'=> '70'),
        array('codigo_dane'=> '70508', 'nombre'=> 'OVEJAS', 'departamento'=> '70'),
        array('codigo_dane'=> '70523', 'nombre'=> 'PALMITO', 'departamento'=> '70'),
        array('codigo_dane'=> '70670', 'nombre'=> 'SAMPUES', 'departamento'=> '70'),
        array('codigo_dane'=> '70678', 'nombre'=> 'SAN BENITO ABAD', 'departamento'=> '70'),
        array('codigo_dane'=> '70702', 'nombre'=> 'SAN JUAN DE BETULIA', 'departamento'=> '70'),
        array('codigo_dane'=> '70708', 'nombre'=> 'SAN MARCOS', 'departamento'=> '70'),
        array('codigo_dane'=> '70713', 'nombre'=> 'SAN ONOFRE', 'departamento'=> '70'),
        array('codigo_dane'=> '70717', 'nombre'=> 'SAN PEDRO', 'departamento'=> '70'),
        array('codigo_dane'=> '70742', 'nombre'=> 'SAN LUIS DE SINCE', 'departamento'=> '70'),
        array('codigo_dane'=> '70771', 'nombre'=> 'SUCRE', 'departamento'=> '70'),
        array('codigo_dane'=> '70820', 'nombre'=> 'SANTIAGO DE TOLU', 'departamento'=> '70'),
        array('codigo_dane'=> '70823', 'nombre'=> 'TOLU VIEJO', 'departamento'=> '70'),
        array('codigo_dane'=> '73001', 'nombre'=> 'IBAGUE', 'departamento'=> '73'),
        array('codigo_dane'=> '73024', 'nombre'=> 'ALPUJARRA', 'departamento'=> '73'),
        array('codigo_dane'=> '73026', 'nombre'=> 'ALVARADO', 'departamento'=> '73'),
        array('codigo_dane'=> '73030', 'nombre'=> 'AMBALEMA', 'departamento'=> '73'),
        array('codigo_dane'=> '73043', 'nombre'=> 'ANZOATEGUI', 'departamento'=> '73'),
        array('codigo_dane'=> '73055', 'nombre'=> 'ARMERO', 'departamento'=> '73'),
        array('codigo_dane'=> '73067', 'nombre'=> 'ATACO', 'departamento'=> '73'),
        array('codigo_dane'=> '73124', 'nombre'=> 'CAJAMARCA', 'departamento'=> '73'),
        array('codigo_dane'=> '73148', 'nombre'=> 'CARMEN DE APICALA', 'departamento'=> '73'),
        array('codigo_dane'=> '73152', 'nombre'=> 'CASABIANCA', 'departamento'=> '73'),
        array('codigo_dane'=> '73168', 'nombre'=> 'CHAPARRAL', 'departamento'=> '73'),
        array('codigo_dane'=> '73200', 'nombre'=> 'COELLO', 'departamento'=> '73'),
        array('codigo_dane'=> '73217', 'nombre'=> 'COYAIMA', 'departamento'=> '73'),
        array('codigo_dane'=> '73226', 'nombre'=> 'CUNDAY', 'departamento'=> '73'),
        array('codigo_dane'=> '73236', 'nombre'=> 'DOLORES', 'departamento'=> '73'),
        array('codigo_dane'=> '73268', 'nombre'=> 'ESPINAL', 'departamento'=> '73'),
        array('codigo_dane'=> '73270', 'nombre'=> 'FALAN', 'departamento'=> '73'),
        array('codigo_dane'=> '73275', 'nombre'=> 'FLANDES', 'departamento'=> '73'),
        array('codigo_dane'=> '73283', 'nombre'=> 'FRESNO', 'departamento'=> '73'),
        array('codigo_dane'=> '73319', 'nombre'=> 'GUAMO', 'departamento'=> '73'),
        array('codigo_dane'=> '73347', 'nombre'=> 'HERVEO', 'departamento'=> '73'),
        array('codigo_dane'=> '73349', 'nombre'=> 'HONDA', 'departamento'=> '73'),
        array('codigo_dane'=> '73352', 'nombre'=> 'ICONONZO', 'departamento'=> '73'),
        array('codigo_dane'=> '73408', 'nombre'=> 'LERIDA', 'departamento'=> '73'),
        array('codigo_dane'=> '73411', 'nombre'=> 'LIBANO', 'departamento'=> '73'),
        array('codigo_dane'=> '73443', 'nombre'=> 'MARIQUITA', 'departamento'=> '73'),
        array('codigo_dane'=> '73449', 'nombre'=> 'MELGAR', 'departamento'=> '73'),
        array('codigo_dane'=> '73461', 'nombre'=> 'MURILLO', 'departamento'=> '73'),
        array('codigo_dane'=> '73483', 'nombre'=> 'NATAGAIMA', 'departamento'=> '73'),
        array('codigo_dane'=> '73504', 'nombre'=> 'ORTEGA', 'departamento'=> '73'),
        array('codigo_dane'=> '73520', 'nombre'=> 'PALOCABILDO', 'departamento'=> '73'),
        array('codigo_dane'=> '73547', 'nombre'=> 'PIEDRAS', 'departamento'=> '73'),
        array('codigo_dane'=> '73555', 'nombre'=> 'PLANADAS', 'departamento'=> '73'),
        array('codigo_dane'=> '73563', 'nombre'=> 'PRADO', 'departamento'=> '73'),
        array('codigo_dane'=> '73585', 'nombre'=> 'PURIFICACION', 'departamento'=> '73'),
        array('codigo_dane'=> '73616', 'nombre'=> 'RIOBLANCO', 'departamento'=> '73'),
        array('codigo_dane'=> '73622', 'nombre'=> 'RONCESVALLES', 'departamento'=> '73'),
        array('codigo_dane'=> '73624', 'nombre'=> 'ROVIRA', 'departamento'=> '73'),
        array('codigo_dane'=> '73671', 'nombre'=> 'SALDAÑA', 'departamento'=> '73'),
        array('codigo_dane'=> '73675', 'nombre'=> 'SAN ANTONIO', 'departamento'=> '73'),
        array('codigo_dane'=> '73678', 'nombre'=> 'SAN LUIS', 'departamento'=> '73'),
        array('codigo_dane'=> '73686', 'nombre'=> 'SANTA ISABEL', 'departamento'=> '73'),
        array('codigo_dane'=> '73770', 'nombre'=> 'SUAREZ', 'departamento'=> '73'),
        array('codigo_dane'=> '73854', 'nombre'=> 'VALLE DE SAN JUAN', 'departamento'=> '73'),
        array('codigo_dane'=> '73861', 'nombre'=> 'VENADILLO', 'departamento'=> '73'),
        array('codigo_dane'=> '73870', 'nombre'=> 'VILLAHERMOSA', 'departamento'=> '73'),
        array('codigo_dane'=> '73873', 'nombre'=> 'VILLARRICA', 'departamento'=> '73'),
        array('codigo_dane'=> '76001', 'nombre'=> 'CALI', 'departamento'=> '76'),
        array('codigo_dane'=> '76020', 'nombre'=> 'ALCALA', 'departamento'=> '76'),
        array('codigo_dane'=> '76036', 'nombre'=> 'ANDALUCIA', 'departamento'=> '76'),
        array('codigo_dane'=> '76041', 'nombre'=> 'ANSERMANUEVO', 'departamento'=> '76'),
        array('codigo_dane'=> '76054', 'nombre'=> 'ARGELIA', 'departamento'=> '76'),
        array('codigo_dane'=> '76100', 'nombre'=> 'BOLIVAR', 'departamento'=> '76'),
        array('codigo_dane'=> '76109', 'nombre'=> 'BUENAVENTURA', 'departamento'=> '76'),
        array('codigo_dane'=> '76111', 'nombre'=> 'GUADALAJARA DE BUGA', 'departamento'=> '76'),
        array('codigo_dane'=> '76113', 'nombre'=> 'BUGALAGRANDE', 'departamento'=> '76'),
        array('codigo_dane'=> '76122', 'nombre'=> 'CAICEDONIA', 'departamento'=> '76'),
        array('codigo_dane'=> '76126', 'nombre'=> 'CALIMA', 'departamento'=> '76'),
        array('codigo_dane'=> '76130', 'nombre'=> 'CANDELARIA', 'departamento'=> '76'),
        array('codigo_dane'=> '76147', 'nombre'=> 'CARTAGO', 'departamento'=> '76'),
        array('codigo_dane'=> '76233', 'nombre'=> 'DAGUA', 'departamento'=> '76'),
        array('codigo_dane'=> '76243', 'nombre'=> 'EL AGUILA', 'departamento'=> '76'),
        array('codigo_dane'=> '76246', 'nombre'=> 'EL CAIRO', 'departamento'=> '76'),
        array('codigo_dane'=> '76248', 'nombre'=> 'EL CERRITO', 'departamento'=> '76'),
        array('codigo_dane'=> '76250', 'nombre'=> 'EL DOVIO', 'departamento'=> '76'),
        array('codigo_dane'=> '76275', 'nombre'=> 'FLORIDA', 'departamento'=> '76'),
        array('codigo_dane'=> '76306', 'nombre'=> 'GINEBRA', 'departamento'=> '76'),
        array('codigo_dane'=> '76318', 'nombre'=> 'GUACARI', 'departamento'=> '76'),
        array('codigo_dane'=> '76364', 'nombre'=> 'JAMUNDI', 'departamento'=> '76'),
        array('codigo_dane'=> '76377', 'nombre'=> 'LA CUMBRE', 'departamento'=> '76'),
        array('codigo_dane'=> '76400', 'nombre'=> 'LA UNION', 'departamento'=> '76'),
        array('codigo_dane'=> '76403', 'nombre'=> 'LA VICTORIA', 'departamento'=> '76'),
        array('codigo_dane'=> '76497', 'nombre'=> 'OBANDO', 'departamento'=> '76'),
        array('codigo_dane'=> '76520', 'nombre'=> 'PALMIRA', 'departamento'=> '76'),
        array('codigo_dane'=> '76563', 'nombre'=> 'PRADERA', 'departamento'=> '76'),
        array('codigo_dane'=> '76606', 'nombre'=> 'RESTREPO', 'departamento'=> '76'),
        array('codigo_dane'=> '76616', 'nombre'=> 'RIOFRIO', 'departamento'=> '76'),
        array('codigo_dane'=> '76622', 'nombre'=> 'ROLDANILLO', 'departamento'=> '76'),
        array('codigo_dane'=> '76670', 'nombre'=> 'SAN PEDRO', 'departamento'=> '76'),
        array('codigo_dane'=> '76736', 'nombre'=> 'SEVILLA', 'departamento'=> '76'),
        array('codigo_dane'=> '76823', 'nombre'=> 'TORO', 'departamento'=> '76'),
        array('codigo_dane'=> '76828', 'nombre'=> 'TRUJILLO', 'departamento'=> '76'),
        array('codigo_dane'=> '76834', 'nombre'=> 'TULUA', 'departamento'=> '76'),
        array('codigo_dane'=> '76845', 'nombre'=> 'ULLOA', 'departamento'=> '76'),
        array('codigo_dane'=> '76863', 'nombre'=> 'VERSALLES', 'departamento'=> '76'),
        array('codigo_dane'=> '76869', 'nombre'=> 'VIJES', 'departamento'=> '76'),
        array('codigo_dane'=> '76890', 'nombre'=> 'YOTOCO', 'departamento'=> '76'),
        array('codigo_dane'=> '76892', 'nombre'=> 'YUMBO', 'departamento'=> '76'),
        array('codigo_dane'=> '76895', 'nombre'=> 'ZARZAL', 'departamento'=> '76'),
        array('codigo_dane'=> '81001', 'nombre'=> 'ARAUCA', 'departamento'=> '81'),
        array('codigo_dane'=> '81065', 'nombre'=> 'ARAUQUITA', 'departamento'=> '81'),
        array('codigo_dane'=> '81220', 'nombre'=> 'CRAVO NORTE', 'departamento'=> '81'),
        array('codigo_dane'=> '81300', 'nombre'=> 'FORTUL', 'departamento'=> '81'),
        array('codigo_dane'=> '81591', 'nombre'=> 'PUERTO RONDON', 'departamento'=> '81'),
        array('codigo_dane'=> '81736', 'nombre'=> 'SARAVENA', 'departamento'=> '81'),
        array('codigo_dane'=> '81794', 'nombre'=> 'TAME', 'departamento'=> '81'),
        array('codigo_dane'=> '85001', 'nombre'=> 'YOPAL', 'departamento'=> '85'),
        array('codigo_dane'=> '85010', 'nombre'=> 'AGUAZUL', 'departamento'=> '85'),
        array('codigo_dane'=> '85015', 'nombre'=> 'CHAMEZA', 'departamento'=> '85'),
        array('codigo_dane'=> '85125', 'nombre'=> 'HATO COROZAL', 'departamento'=> '85'),
        array('codigo_dane'=> '85136', 'nombre'=> 'LA SALINA', 'departamento'=> '85'),
        array('codigo_dane'=> '85139', 'nombre'=> 'MANI', 'departamento'=> '85'),
        array('codigo_dane'=> '85162', 'nombre'=> 'MONTERREY', 'departamento'=> '85'),
        array('codigo_dane'=> '85225', 'nombre'=> 'NUNCHIA', 'departamento'=> '85'),
        array('codigo_dane'=> '85230', 'nombre'=> 'OROCUE', 'departamento'=> '85'),
        array('codigo_dane'=> '85250', 'nombre'=> 'PAZ DE ARIPORO', 'departamento'=> '85'),
        array('codigo_dane'=> '85263', 'nombre'=> 'PORE', 'departamento'=> '85'),
        array('codigo_dane'=> '85279', 'nombre'=> 'RECETOR', 'departamento'=> '85'),
        array('codigo_dane'=> '85300', 'nombre'=> 'SABANALARGA', 'departamento'=> '85'),
        array('codigo_dane'=> '85315', 'nombre'=> 'SACAMA', 'departamento'=> '85'),
        array('codigo_dane'=> '85325', 'nombre'=> 'SAN LUIS DE PALENQUE', 'departamento'=> '85'),
        array('codigo_dane'=> '85400', 'nombre'=> 'TAMARA', 'departamento'=> '85'),
        array('codigo_dane'=> '85410', 'nombre'=> 'TAURAMENA', 'departamento'=> '85'),
        array('codigo_dane'=> '85430', 'nombre'=> 'TRINIDAD', 'departamento'=> '85'),
        array('codigo_dane'=> '85440', 'nombre'=> 'VILLANUEVA', 'departamento'=> '85'),
        array('codigo_dane'=> '86001', 'nombre'=> 'MOCOA', 'departamento'=> '86'),
        array('codigo_dane'=> '86219', 'nombre'=> 'COLON', 'departamento'=> '86'),
        array('codigo_dane'=> '86320', 'nombre'=> 'ORITO', 'departamento'=> '86'),
        array('codigo_dane'=> '86568', 'nombre'=> 'PUERTO ASIS', 'departamento'=> '86'),
        array('codigo_dane'=> '86569', 'nombre'=> 'PUERTO CAICEDO', 'departamento'=> '86'),
        array('codigo_dane'=> '86571', 'nombre'=> 'PUERTO GUZMAN', 'departamento'=> '86'),
        array('codigo_dane'=> '86573', 'nombre'=> 'LEGUIZAMO', 'departamento'=> '86'),
        array('codigo_dane'=> '86749', 'nombre'=> 'SIBUNDOY', 'departamento'=> '86'),
        array('codigo_dane'=> '86755', 'nombre'=> 'SAN FRANCISCO', 'departamento'=> '86'),
        array('codigo_dane'=> '86757', 'nombre'=> 'SAN MIGUEL', 'departamento'=> '86'),
        array('codigo_dane'=> '86760', 'nombre'=> 'SANTIAGO', 'departamento'=> '86'),
        array('codigo_dane'=> '86865', 'nombre'=> 'VALLE DEL GUAMUEZ', 'departamento'=> '86'),
        array('codigo_dane'=> '86885', 'nombre'=> 'VILLAGARZON', 'departamento'=> '86'),
        array('codigo_dane'=> '88001', 'nombre'=> 'SAN ANDRES', 'departamento'=> '88'),
        array('codigo_dane'=> '88564', 'nombre'=> 'PROVIDENCIA', 'departamento'=> '88'),
        array('codigo_dane'=> '91001', 'nombre'=> 'LETICIA', 'departamento'=> '91'),
        array('codigo_dane'=> '91263', 'nombre'=> 'EL ENCANTO', 'departamento'=> '91'),
        array('codigo_dane'=> '91405', 'nombre'=> 'LA CHORRERA', 'departamento'=> '91'),
        array('codigo_dane'=> '91407', 'nombre'=> 'LA PEDRERA', 'departamento'=> '91'),
        array('codigo_dane'=> '91430', 'nombre'=> 'LA VICTORIA', 'departamento'=> '91'),
        array('codigo_dane'=> '91460', 'nombre'=> 'MIRITI - PARANA', 'departamento'=> '91'),
        array('codigo_dane'=> '91530', 'nombre'=> 'PUERTO ALEGRIA', 'departamento'=> '91'),
        array('codigo_dane'=> '91536', 'nombre'=> 'PUERTO ARICA', 'departamento'=> '91'),
        array('codigo_dane'=> '91540', 'nombre'=> 'PUERTO NARIÑO', 'departamento'=> '91'),
        array('codigo_dane'=> '91669', 'nombre'=> 'PUERTO SANTANDER', 'departamento'=> '91'),
        array('codigo_dane'=> '91798', 'nombre'=> 'TARAPACA', 'departamento'=> '91'),
        array('codigo_dane'=> '94001', 'nombre'=> 'INIRIDA', 'departamento'=> '94'),
        array('codigo_dane'=> '94343', 'nombre'=> 'BARRANCO MINAS', 'departamento'=> '94'),
        array('codigo_dane'=> '94663', 'nombre'=> 'MAPIRIPANA', 'departamento'=> '94'),
        array('codigo_dane'=> '94883', 'nombre'=> 'SAN FELIPE', 'departamento'=> '94'),
        array('codigo_dane'=> '94884', 'nombre'=> 'PUERTO COLOMBIA', 'departamento'=> '94'),
        array('codigo_dane'=> '94885', 'nombre'=> 'LA GUADALUPE', 'departamento'=> '94'),
        array('codigo_dane'=> '94886', 'nombre'=> 'CACAHUAL', 'departamento'=> '94'),
        array('codigo_dane'=> '94887', 'nombre'=> 'PANA PANA', 'departamento'=> '94'),
        array('codigo_dane'=> '94888', 'nombre'=> 'MORICHAL', 'departamento'=> '94'),
        array('codigo_dane'=> '95001', 'nombre'=> 'SAN JOSE DEL GUAVIARE', 'departamento'=> '95'),
        array('codigo_dane'=> '95015', 'nombre'=> 'CALAMAR', 'departamento'=> '95'),
        array('codigo_dane'=> '95025', 'nombre'=> 'EL RETORNO', 'departamento'=> '95'),
        array('codigo_dane'=> '95200', 'nombre'=> 'MIRAFLORES', 'departamento'=> '95'),
        array('codigo_dane'=> '97001', 'nombre'=> 'MITU', 'departamento'=> '97'),
        array('codigo_dane'=> '97161', 'nombre'=> 'CARURU', 'departamento'=> '97'),
        array('codigo_dane'=> '97511', 'nombre'=> 'PACOA', 'departamento'=> '97'),
        array('codigo_dane'=> '97666', 'nombre'=> 'TARAIRA', 'departamento'=> '97'),
        array('codigo_dane'=> '97777', 'nombre'=> 'PAPUNAUA', 'departamento'=> '97'),
        array('codigo_dane'=> '97889', 'nombre'=> 'YAVARATE', 'departamento'=> '97'),
        array('codigo_dane'=> '99001', 'nombre'=> 'PUERTO CARREÑO', 'departamento'=> '99'),
        array('codigo_dane'=> '99524', 'nombre'=> 'LA PRIMAVERA', 'departamento'=> '99'),
        array('codigo_dane'=> '99624', 'nombre'=> 'SANTA ROSALIA', 'departamento'=> '99'),
        array('codigo_dane'=> '99773', 'nombre'=> 'CUMARIBO', 'departamento'=> '99'),
    );

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->data as $value) {
            $tipo= new Municipios($value);
            $tipo->save();
        }
    }
}
